//! Metric type registry.
//!
//! Central enumeration of every counter and gauge key. Recording and
//! lookup logic lives in sibling modules; this file only declares names.

/// Type of indicator
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MetricType {
    NumAuthFailedSessions,
    NumQueries,
    NumActiveQueries,
    QueryParseTimeUs,
    QueryValidateTimeUs,
    QueryPlanTimeUs,
    QueryOptimizeTimeUs,
    QueryExecuteTimeUs,
    QueryTotalTimeUs,
    QueryPlanNodeCount,
    QueryResultRowCount,
    // Query Type Statistics
    NumMatchQueries,
    NumCreateQueries,
    NumUpdateQueries,
    NumDeleteQueries,
    NumInsertQueries,
    NumGoQueries,
    NumFetchQueries,
    NumLookupQueries,
    NumShowQueries,
    // Search metrics
    NumSearchQueries,
    NumSearchErrors,
    SearchLatencyMs,
    NumIndexOperations,
    NumIndexErrors,
    IndexLatencyMs,
    NumDeleteOperations,
    NumDeleteErrors,
    DeleteLatencyMs,
    SearchResultCount,
    SearchCacheHitCount,
    SearchCacheMissCount,
    // Classified search errors
    SearchErrorIndexNotFound,
    SearchErrorEngineError,
    SearchErrorIoError,
    SearchErrorSerialization,
    SearchErrorInternal,
    // Storage metrics
    StorageReadOps,
    StorageWriteOps,
    StorageReadLatencyUs,
    StorageWriteLatencyUs,
    StorageErrors,
    // Transaction metrics
    TxnBeginCount,
    TxnCommitCount,
    TxnRollbackCount,
    TxnActiveCount,
    TxnConflictCount,
    TxnTimeoutCount,
    TxnDisconnectCount,
    TxnRecoveryAbortCount,
    TxnCleanupFailureCount,
    TxnActiveStatements,
    TxnActiveSnapshots,
    TxnPendingWrites,
    TxnFrontierLag,
    TxnStagedWalBytes,
    TxnUndoBytes,
    TxnCheckpointDrainTimeMs,
    // Checkpoint metrics
    CheckpointTriggerCount,
    CheckpointSuccessCount,
    CheckpointFailureCount,
    CheckpointDurationUs,
    CheckpointDataFlushedBytes,
    CheckpointWalFilesTruncated,
    CheckpointTriggerAgeSecs,
    CheckpointTriggeredByWalSize,
    CheckpointTriggeredByInterval,
    CheckpointTriggeredExplicit,
    CheckpointRequestsDeduplicated,
    CheckpointRequestsBlocked,
    // Sync metrics
    SyncOperations,
    SyncLatencyMs,
    SyncErrors,
    SyncQueueDepth,
    OutboxPending,
    OutboxRetryCount,
    OutboxDeadLetterCount,
    OutboxLeasedCount,
    OutboxOldestEventAgeMs,
    OutboxFrontierLag,
    OutboxDegraded,
    TargetFrontierLag,
    GenerationBuildCount,
    GenerationPublishCount,
    GenerationRebuildFailures,
    InconsistentIndexCount,
    RebuildPhaseLatencyMs,
    RebuildPhaseOps,
    SplitCount,
    SplitFailures,
    ReclaimedIndexFiles,
    ManifestActiveReaders,
    ManifestRetiredGenerations,
    FenceFailures,
    TransportLatencyMs,
    TransportOps,
    MaterializerLatencyMs,
    MaterializerOps,
    SnapshotLag,
    // Index metrics
    IndexScanCount,
    IndexLookupLatencyUs,
    IndexMemoryUsage,
    IndexWriteOps,
    IndexWriteLatencyUs,
    // Vector metrics
    VectorSearchOps,
    VectorSearchErrors,
    VectorSearchLatencyMs,
    VectorUpsertOps,
    VectorUpsertErrors,
    VectorUpsertLatencyMs,
    VectorDeleteOps,
    VectorDeleteErrors,
    VectorDeleteLatencyMs,
    /// Local vector engine: adjacency/list write-lock acquisitions (only
    /// populated when the `lock-metrics` feature is enabled).
    VectorLockOps,
    /// Local vector engine: cumulative wait time of those acquisitions, in
    /// microseconds (requires the `lock-metrics` feature).
    VectorLockLatencyUs,
    /// Local vector engine: HNSW adjacency reads where the version
    /// double-read detected a concurrent mutation and reloaded.
    VectorVersionReloads,
    VectorBufferFlushOps,
    VectorBufferFlushLatencyMs,
    VectorEmbeddingOps,
    VectorEmbeddingErrors,
    VectorEmbeddingLatencyMs,
    /// Cumulative prompt tokens reported by embedding calls.
    VectorEmbeddingPromptTokens,
    /// Cumulative total tokens reported by embedding calls.
    VectorEmbeddingTotalTokens,
    /// Post-recall rerank calls issued.
    VectorRerankOps,
    /// Failed post-recall rerank calls (recall order kept).
    VectorRerankErrors,
    /// Cumulative rerank call latency in milliseconds.
    VectorRerankLatencyMs,
    VectorDisabledSkips,
    // MVCC Tombstone metrics
    TombstoneCount,
    TombstoneMemoryBytes,
    TombstoneOldestTsMin,
    TombstoneNewestTsMax,
    TombstoneActiveSnapshots,
    // Storage fragmentation metrics (single wasted-share caliber)
    FragmentationRatioPermille,
    TopologyWastedBytes,
    // Migration metrics
    MigrationTotalCount,
    MigrationRowsMigrated,
    MigrationDurationMs,
    MigrationErrorsTotal,
    MigrationActiveCount,
    // Dirty page / incremental checkpoint metrics
    DirtyPagesTotal,
    DirtyPagesCount,
    DirtyPageRatioPermille,
    CheckpointStrategyIncremental,
    CheckpointStrategyHybrid,
    CheckpointStrategyFull,
    CheckpointIncrementalDurationUs,
    CheckpointIncrementalBytesFlushed,
    // Factorization metrics
    FactorizationFlattenTotal,
    FactorizationFallbackTotal,
    FactorizationPhysicalMappingFallbackTotal,
    // Bloom filter metrics (range-scan skip)
    BloomQueries,
    BloomHits,
    BloomHitRatePermille,
    // Edge orphan audit observability
    EdgeOrphanRows,
    EdgeOrphanMappings,
    EdgeLiveAuthorityOrphans,
    EdgeRelocatedOrphans,
    // Import discard observability
    ImportDroppedRows,
    ImportAcceptedRows,
    // Snapshot cache fallback observability
    SnapshotFallbackCount,
    // Edge secondary index lag observability
    EdgeIndexLag,
    EdgeIndexStaleSecs,
}

impl MetricType {
    /// Stable Prometheus series name for this metric.
    ///
    /// Every variant maps to one `linkrs_` prefixed snake_case name; adding a
    /// variant without a name is a compile error, so the export surface can
    /// never silently drop a counter.
    pub fn prometheus_name(&self) -> &'static str {
        match self {
            Self::NumAuthFailedSessions => "linkrs_auth_failed_sessions",
            Self::NumQueries => "linkrs_queries_total",
            Self::NumActiveQueries => "linkrs_active_queries",
            Self::QueryParseTimeUs => "linkrs_query_parse_time_us_total",
            Self::QueryValidateTimeUs => "linkrs_query_validate_time_us_total",
            Self::QueryPlanTimeUs => "linkrs_query_plan_time_us_total",
            Self::QueryOptimizeTimeUs => "linkrs_query_optimize_time_us_total",
            Self::QueryExecuteTimeUs => "linkrs_query_execute_time_us_total",
            Self::QueryTotalTimeUs => "linkrs_query_total_time_us_total",
            Self::QueryPlanNodeCount => "linkrs_query_plan_node_count",
            Self::QueryResultRowCount => "linkrs_query_result_rows",
            Self::NumMatchQueries => "linkrs_queries_by_type_match_total",
            Self::NumCreateQueries => "linkrs_queries_by_type_create_total",
            Self::NumUpdateQueries => "linkrs_queries_by_type_update_total",
            Self::NumDeleteQueries => "linkrs_queries_by_type_delete_total",
            Self::NumInsertQueries => "linkrs_queries_by_type_insert_total",
            Self::NumGoQueries => "linkrs_queries_by_type_go_total",
            Self::NumFetchQueries => "linkrs_queries_by_type_fetch_total",
            Self::NumLookupQueries => "linkrs_queries_by_type_lookup_total",
            Self::NumShowQueries => "linkrs_queries_by_type_show_total",
            Self::NumSearchQueries => "linkrs_search_ops_total",
            Self::NumSearchErrors => "linkrs_search_errors_total",
            Self::SearchLatencyMs => "linkrs_search_latency_ms_total",
            Self::NumIndexOperations => "linkrs_index_operations_total",
            Self::NumIndexErrors => "linkrs_index_errors_total",
            Self::IndexLatencyMs => "linkrs_index_latency_ms_total",
            Self::NumDeleteOperations => "linkrs_delete_operations_total",
            Self::NumDeleteErrors => "linkrs_delete_errors_total",
            Self::DeleteLatencyMs => "linkrs_delete_latency_ms_total",
            Self::SearchResultCount => "linkrs_search_result_count",
            Self::SearchCacheHitCount => "linkrs_search_cache_hits_total",
            Self::SearchCacheMissCount => "linkrs_search_cache_misses_total",
            Self::SearchErrorIndexNotFound => "linkrs_search_errors_index_not_found_total",
            Self::SearchErrorEngineError => "linkrs_search_errors_engine_total",
            Self::SearchErrorIoError => "linkrs_search_errors_io_total",
            Self::SearchErrorSerialization => "linkrs_search_errors_serialization_total",
            Self::SearchErrorInternal => "linkrs_search_errors_internal_total",
            Self::StorageReadOps => "linkrs_storage_read_ops_total",
            Self::StorageWriteOps => "linkrs_storage_write_ops_total",
            Self::StorageReadLatencyUs => "linkrs_storage_read_latency_us_total",
            Self::StorageWriteLatencyUs => "linkrs_storage_write_latency_us_total",
            Self::StorageErrors => "linkrs_storage_errors_total",
            Self::TxnBeginCount => "linkrs_txn_begin_total",
            Self::TxnCommitCount => "linkrs_txn_commit_total",
            Self::TxnRollbackCount => "linkrs_txn_rollback_total",
            Self::TxnActiveCount => "linkrs_txn_active",
            Self::TxnConflictCount => "linkrs_txn_conflicts_total",
            Self::TxnTimeoutCount => "linkrs_txn_timeouts_total",
            Self::TxnDisconnectCount => "linkrs_txn_disconnects_total",
            Self::TxnRecoveryAbortCount => "linkrs_txn_recovery_aborts_total",
            Self::TxnCleanupFailureCount => "linkrs_txn_cleanup_failures_total",
            Self::TxnActiveStatements => "linkrs_txn_active_statements",
            Self::TxnActiveSnapshots => "linkrs_txn_active_snapshots",
            Self::TxnPendingWrites => "linkrs_txn_pending_writes",
            Self::TxnFrontierLag => "linkrs_txn_frontier_lag",
            Self::TxnStagedWalBytes => "linkrs_txn_staged_wal_bytes",
            Self::TxnUndoBytes => "linkrs_txn_undo_bytes",
            Self::TxnCheckpointDrainTimeMs => "linkrs_txn_checkpoint_drain_time_ms_total",
            Self::CheckpointTriggerCount => "linkrs_checkpoint_triggered_total",
            Self::CheckpointSuccessCount => "linkrs_checkpoint_success_total",
            Self::CheckpointFailureCount => "linkrs_checkpoint_failure_total",
            Self::CheckpointDurationUs => "linkrs_checkpoint_duration_us_total",
            Self::CheckpointDataFlushedBytes => "linkrs_checkpoint_flushed_bytes_total",
            Self::CheckpointWalFilesTruncated => "linkrs_checkpoint_wal_files_truncated_total",
            Self::CheckpointTriggerAgeSecs => "linkrs_checkpoint_trigger_age_secs",
            Self::CheckpointTriggeredByWalSize => "linkrs_checkpoint_triggered_by_wal_size_total",
            Self::CheckpointTriggeredByInterval => "linkrs_checkpoint_triggered_by_interval_total",
            Self::CheckpointTriggeredExplicit => "linkrs_checkpoint_triggered_explicit_total",
            Self::CheckpointRequestsDeduplicated => "linkrs_checkpoint_deduplicated_total",
            Self::CheckpointRequestsBlocked => "linkrs_checkpoint_blocked_total",
            Self::SyncOperations => "linkrs_sync_operations_total",
            Self::SyncLatencyMs => "linkrs_sync_latency_ms_total",
            Self::SyncErrors => "linkrs_sync_errors_total",
            Self::SyncQueueDepth => "linkrs_sync_queue_depth",
            Self::OutboxPending => "linkrs_sync_outbox_pending",
            Self::OutboxRetryCount => "linkrs_sync_outbox_retries_total",
            Self::OutboxDeadLetterCount => "linkrs_sync_outbox_dead_letters",
            Self::OutboxLeasedCount => "linkrs_sync_outbox_leased",
            Self::OutboxOldestEventAgeMs => "linkrs_sync_outbox_oldest_event_age_ms",
            Self::OutboxFrontierLag => "linkrs_sync_outbox_frontier_lag",
            Self::OutboxDegraded => "linkrs_sync_outbox_degraded",
            Self::TargetFrontierLag => "linkrs_sync_target_frontier_lag",
            Self::GenerationBuildCount => "linkrs_sync_generation_builds_total",
            Self::GenerationPublishCount => "linkrs_sync_generation_publishes_total",
            Self::GenerationRebuildFailures => "linkrs_sync_generation_rebuild_failures_total",
            Self::InconsistentIndexCount => "linkrs_sync_inconsistent_indexes",
            Self::RebuildPhaseLatencyMs => "linkrs_sync_rebuild_phase_latency_ms_total",
            Self::RebuildPhaseOps => "linkrs_sync_rebuild_phase_ops_total",
            Self::SplitCount => "linkrs_sync_splits_total",
            Self::SplitFailures => "linkrs_sync_split_failures_total",
            Self::ReclaimedIndexFiles => "linkrs_sync_reclaimed_index_files_total",
            Self::ManifestActiveReaders => "linkrs_sync_manifest_active_readers",
            Self::ManifestRetiredGenerations => "linkrs_sync_manifest_retired_generations",
            Self::FenceFailures => "linkrs_sync_fence_failures_total",
            Self::TransportLatencyMs => "linkrs_sync_transport_latency_ms_total",
            Self::TransportOps => "linkrs_sync_transport_ops_total",
            Self::MaterializerLatencyMs => "linkrs_sync_materializer_latency_ms_total",
            Self::MaterializerOps => "linkrs_sync_materializer_ops_total",
            Self::SnapshotLag => "linkrs_sync_snapshot_lag",
            Self::IndexScanCount => "linkrs_index_scan_total",
            Self::IndexLookupLatencyUs => "linkrs_index_lookup_latency_us_total",
            Self::IndexMemoryUsage => "linkrs_index_memory_usage_bytes",
            Self::IndexWriteOps => "linkrs_index_write_ops_total",
            Self::IndexWriteLatencyUs => "linkrs_index_write_latency_us_total",
            Self::VectorSearchOps => "linkrs_vector_search_ops_total",
            Self::VectorSearchErrors => "linkrs_vector_search_errors_total",
            Self::VectorSearchLatencyMs => "linkrs_vector_search_latency_ms_total",
            Self::VectorUpsertOps => "linkrs_vector_upsert_ops_total",
            Self::VectorUpsertErrors => "linkrs_vector_upsert_errors_total",
            Self::VectorUpsertLatencyMs => "linkrs_vector_upsert_latency_ms_total",
            Self::VectorDeleteOps => "linkrs_vector_delete_ops_total",
            Self::VectorDeleteErrors => "linkrs_vector_delete_errors_total",
            Self::VectorDeleteLatencyMs => "linkrs_vector_delete_latency_ms_total",
            Self::VectorLockOps => "linkrs_vector_lock_ops_total",
            Self::VectorLockLatencyUs => "linkrs_vector_lock_latency_us_total",
            Self::VectorVersionReloads => "linkrs_vector_version_reloads_total",
            Self::VectorBufferFlushOps => "linkrs_vector_buffer_flush_ops_total",
            Self::VectorBufferFlushLatencyMs => "linkrs_vector_buffer_flush_latency_ms_total",
            Self::VectorEmbeddingOps => "linkrs_vector_embedding_ops_total",
            Self::VectorEmbeddingErrors => "linkrs_vector_embedding_errors_total",
            Self::VectorEmbeddingLatencyMs => "linkrs_vector_embedding_latency_ms_total",
            Self::VectorEmbeddingPromptTokens => "linkrs_vector_embedding_prompt_tokens_total",
            Self::VectorEmbeddingTotalTokens => "linkrs_vector_embedding_total_tokens_total",
            Self::VectorRerankOps => "linkrs_vector_rerank_ops_total",
            Self::VectorRerankErrors => "linkrs_vector_rerank_errors_total",
            Self::VectorRerankLatencyMs => "linkrs_vector_rerank_latency_ms_total",
            Self::VectorDisabledSkips => "linkrs_vector_disabled_skips_total",
            Self::TombstoneCount => "linkrs_tombstone_count",
            Self::TombstoneMemoryBytes => "linkrs_tombstone_memory_bytes",
            Self::TombstoneOldestTsMin => "linkrs_tombstone_oldest_ts_min",
            Self::TombstoneNewestTsMax => "linkrs_tombstone_newest_ts_max",
            Self::TombstoneActiveSnapshots => "linkrs_tombstone_active_snapshots",
            Self::FragmentationRatioPermille => "linkrs_fragmentation_ratio_permille",
            Self::TopologyWastedBytes => "linkrs_topology_wasted_bytes",
            Self::MigrationTotalCount => "linkrs_migration_total",
            Self::MigrationRowsMigrated => "linkrs_migration_rows_total",
            Self::MigrationDurationMs => "linkrs_migration_duration_ms_total",
            Self::MigrationErrorsTotal => "linkrs_migration_errors_total",
            Self::MigrationActiveCount => "linkrs_migration_active",
            Self::DirtyPagesTotal => "linkrs_dirty_pages_total",
            Self::DirtyPagesCount => "linkrs_dirty_pages",
            Self::DirtyPageRatioPermille => "linkrs_dirty_page_ratio_permille",
            Self::CheckpointStrategyIncremental => "linkrs_checkpoint_strategy_incremental_total",
            Self::CheckpointStrategyHybrid => "linkrs_checkpoint_strategy_hybrid_total",
            Self::CheckpointStrategyFull => "linkrs_checkpoint_strategy_full_total",
            Self::CheckpointIncrementalDurationUs => {
                "linkrs_checkpoint_incremental_duration_us_total"
            }
            Self::CheckpointIncrementalBytesFlushed => "linkrs_checkpoint_incremental_bytes_total",
            Self::FactorizationFlattenTotal => "linkrs_factorization_flatten_total",
            Self::FactorizationFallbackTotal => "linkrs_factorization_fallback_total",
            Self::FactorizationPhysicalMappingFallbackTotal => {
                "linkrs_factorization_physical_mapping_fallback_total"
            }
            Self::BloomQueries => "linkrs_bloom_queries_total",
            Self::BloomHits => "linkrs_bloom_hits_total",
            Self::BloomHitRatePermille => "linkrs_bloom_hit_rate_permille",
            Self::EdgeOrphanRows => "linkrs_edge_orphan_rows",
            Self::EdgeOrphanMappings => "linkrs_edge_orphan_mappings",
            Self::EdgeLiveAuthorityOrphans => "linkrs_edge_live_authority_orphans",
            Self::EdgeRelocatedOrphans => "linkrs_edge_relocated_orphans",
            Self::ImportDroppedRows => "linkrs_import_dropped_rows_total",
            Self::ImportAcceptedRows => "linkrs_import_accepted_rows_total",
            Self::SnapshotFallbackCount => "linkrs_snapshot_fallback_total",
            Self::EdgeIndexLag => "linkrs_edge_index_lag",
            Self::EdgeIndexStaleSecs => "linkrs_edge_index_stale_secs",
        }
    }
}
