//! Metric type registry.
//!
//! Central enumeration of every counter and gauge key. Recording and
//! lookup logic lives in sibling modules; this file only declares names.

/// Type of indicator
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MetricType {
    NumAuthFailedSessions,
    NumQueries,
    NumActiveQueries,
    QueryParseTimeUs,
    QueryValidateTimeUs,
    QueryPlanTimeUs,
    QueryOptimizeTimeUs,
    QueryExecuteTimeUs,
    QueryTotalTimeUs,
    QueryPlanNodeCount,
    QueryResultRowCount,
    // Query Type Statistics
    NumMatchQueries,
    NumCreateQueries,
    NumUpdateQueries,
    NumDeleteQueries,
    NumInsertQueries,
    NumGoQueries,
    NumFetchQueries,
    NumLookupQueries,
    NumShowQueries,
    // Search metrics
    NumSearchQueries,
    NumSearchErrors,
    SearchLatencyMs,
    NumIndexOperations,
    NumIndexErrors,
    IndexLatencyMs,
    NumDeleteOperations,
    NumDeleteErrors,
    DeleteLatencyMs,
    SearchResultCount,
    SearchCacheHitCount,
    SearchCacheMissCount,
    // Classified search errors
    SearchErrorIndexNotFound,
    SearchErrorEngineError,
    SearchErrorIoError,
    SearchErrorSerialization,
    SearchErrorInternal,
    // Storage metrics
    StorageReadOps,
    StorageWriteOps,
    StorageReadLatencyUs,
    StorageWriteLatencyUs,
    StorageErrors,
    // Transaction metrics
    TxnBeginCount,
    TxnCommitCount,
    TxnRollbackCount,
    TxnActiveCount,
    TxnConflictCount,
    TxnTimeoutCount,
    TxnDisconnectCount,
    TxnRecoveryAbortCount,
    TxnCleanupFailureCount,
    TxnActiveStatements,
    TxnActiveSnapshots,
    TxnPendingWrites,
    TxnFrontierLag,
    TxnStagedWalBytes,
    TxnUndoBytes,
    TxnCheckpointDrainTimeMs,
    // Checkpoint metrics
    CheckpointTriggerCount,
    CheckpointSuccessCount,
    CheckpointFailureCount,
    CheckpointDurationUs,
    CheckpointDataFlushedBytes,
    CheckpointWalFilesTruncated,
    CheckpointTriggerAgeSecs,
    CheckpointTriggeredByWalSize,
    CheckpointTriggeredByInterval,
    CheckpointTriggeredExplicit,
    CheckpointRequestsDeduplicated,
    CheckpointRequestsBlocked,
    // Sync metrics
    SyncOperations,
    SyncLatencyMs,
    SyncErrors,
    SyncQueueDepth,
    OutboxPending,
    OutboxRetryCount,
    OutboxDeadLetterCount,
    OutboxLeasedCount,
    OutboxOldestEventAgeMs,
    OutboxFrontierLag,
    OutboxDegraded,
    TargetFrontierLag,
    GenerationBuildCount,
    GenerationPublishCount,
    GenerationRebuildFailures,
    InconsistentIndexCount,
    RebuildPhaseLatencyMs,
    RebuildPhaseOps,
    SplitCount,
    SplitFailures,
    ReclaimedIndexFiles,
    ManifestActiveReaders,
    ManifestRetiredGenerations,
    FenceFailures,
    TransportLatencyMs,
    TransportOps,
    MaterializerLatencyMs,
    MaterializerOps,
    SnapshotLag,
    // Index metrics
    IndexScanCount,
    IndexLookupLatencyUs,
    IndexMemoryUsage,
    IndexWriteOps,
    IndexWriteLatencyUs,
    // Vector metrics
    VectorSearchOps,
    VectorSearchErrors,
    VectorSearchLatencyMs,
    VectorUpsertOps,
    VectorUpsertErrors,
    VectorUpsertLatencyMs,
    VectorDeleteOps,
    VectorDeleteErrors,
    VectorDeleteLatencyMs,
    /// Local vector engine: adjacency/list write-lock acquisitions (only
    /// populated when the `lock-metrics` feature is enabled).
    VectorLockOps,
    /// Local vector engine: cumulative wait time of those acquisitions, in
    /// microseconds (requires the `lock-metrics` feature).
    VectorLockLatencyUs,
    /// Local vector engine: HNSW adjacency reads where the version
    /// double-read detected a concurrent mutation and reloaded.
    VectorVersionReloads,
    VectorBufferFlushOps,
    VectorBufferFlushLatencyMs,
    VectorEmbeddingOps,
    VectorEmbeddingErrors,
    VectorEmbeddingLatencyMs,
    /// Cumulative prompt tokens reported by embedding calls.
    VectorEmbeddingPromptTokens,
    /// Cumulative total tokens reported by embedding calls.
    VectorEmbeddingTotalTokens,
    /// Post-recall rerank calls issued.
    VectorRerankOps,
    /// Failed post-recall rerank calls (recall order kept).
    VectorRerankErrors,
    /// Cumulative rerank call latency in milliseconds.
    VectorRerankLatencyMs,
    VectorDisabledSkips,
    // MVCC Tombstone metrics
    TombstoneCount,
    TombstoneMemoryBytes,
    TombstoneOldestTsMin,
    TombstoneNewestTsMax,
    TombstoneActiveSnapshots,
    // Storage fragmentation metrics (single wasted-share caliber)
    FragmentationRatioPermille,
    TopologyWastedBytes,
    // Migration metrics
    MigrationTotalCount,
    MigrationRowsMigrated,
    MigrationDurationMs,
    MigrationErrorsTotal,
    MigrationActiveCount,
    // Dirty page / incremental checkpoint metrics
    DirtyPagesTotal,
    DirtyPagesCount,
    DirtyPageRatioPermille,
    CheckpointStrategyIncremental,
    CheckpointStrategyHybrid,
    CheckpointStrategyFull,
    CheckpointIncrementalDurationUs,
    CheckpointIncrementalBytesFlushed,
    // Factorization metrics
    FactorizationFlattenTotal,
    FactorizationFallbackTotal,
    FactorizationPhysicalMappingFallbackTotal,
    // Bloom filter metrics (range-scan skip)
    BloomQueries,
    BloomHits,
    BloomHitRatePermille,
    // Edge orphan audit observability
    EdgeOrphanRows,
    EdgeOrphanMappings,
    EdgeLiveAuthorityOrphans,
    EdgeRelocatedOrphans,
    // Import discard observability
    ImportDroppedRows,
    ImportAcceptedRows,
    // Snapshot cache fallback observability
    SnapshotFallbackCount,
    // Edge secondary index lag observability
    EdgeIndexLag,
    EdgeIndexStaleSecs,
}
