use std::collections::HashMap;

use crate::utils::error::{CliError, Result};

#[derive(Debug, Clone)]
pub enum SpecialVarType {
    Boolean,
    Enum { values: Vec<String> },
    Number { min: i64, max: i64 },
    String,
}

#[derive(Debug, Clone)]
pub struct SpecialVariable {
    pub name: String,
    pub default_value: String,
    pub description: String,
    pub var_type: SpecialVarType,
}

impl SpecialVariable {
    pub fn new(name: &str, default: &str, var_type: SpecialVarType, desc: &str) -> Self {
        Self {
            name: name.to_string(),
            default_value: default.to_string(),
            description: desc.to_string(),
            var_type,
        }
    }

    pub fn validate(&self, value: &str) -> Result<String> {
        match &self.var_type {
            SpecialVarType::Boolean => {
                let lower = value.to_lowercase();
                match lower.as_str() {
                    "on" | "true" | "yes" | "1" => Ok("on".to_string()),
                    "off" | "false" | "no" | "0" => Ok("off".to_string()),
                    _ => Err(CliError::Other(format!(
                        "Invalid boolean value '{}' for {}. Use on/off.",
                        value, self.name
                    ))),
                }
            }
            SpecialVarType::Enum { values } => {
                let lower = value.to_lowercase();
                if values.iter().any(|v| v.to_lowercase() == lower) {
                    Ok(lower)
                } else {
                    Err(CliError::Other(format!(
                        "Invalid value '{}' for {}. Valid values: {}",
                        value,
                        self.name,
                        values.join(", ")
                    )))
                }
            }
            SpecialVarType::Number { min, max } => {
                let num: i64 = value.parse().map_err(|_| {
                    CliError::Other(format!(
                        "Invalid number '{}' for {}. Must be {}-{}.",
                        value, self.name, min, max
                    ))
                })?;
                if num < *min || num > *max {
                    return Err(CliError::Other(format!(
                        "Value {} out of range for {}. Must be {}-{}.",
                        num, self.name, min, max
                    )));
                }
                Ok(value.to_string())
            }
            SpecialVarType::String => Ok(value.to_string()),
        }
    }
}

pub fn define_special_variables() -> Vec<SpecialVariable> {
    vec![
        SpecialVariable::new(
            "ON_ERROR_STOP",
            "off",
            SpecialVarType::Boolean,
            "Stop execution on error (script mode)",
        ),
        SpecialVariable::new(
            "ECHO",
            "none",
            SpecialVarType::Enum {
                values: vec!["none".into(), "queries".into(), "all".into()],
            },
            "Echo mode: none, queries, all",
        ),
        SpecialVariable::new(
            "ECHO_HIDDEN",
            "off",
            SpecialVarType::Boolean,
            "Echo internal queries generated by meta-commands",
        ),
        SpecialVariable::new(
            "QUIET",
            "off",
            SpecialVarType::Boolean,
            "Quiet mode - suppress non-essential output",
        ),
        SpecialVariable::new(
            "TIMING",
            "off",
            SpecialVarType::Boolean,
            "Display query execution time",
        ),
        SpecialVariable::new(
            "SINGLELINE",
            "off",
            SpecialVarType::Boolean,
            "Single-line mode - execute on Enter",
        ),
        SpecialVariable::new(
            "SYNTAX_HL",
            "on",
            SpecialVarType::Boolean,
            "Enable syntax highlighting",
        ),
        SpecialVariable::new(
            "HISTSIZE",
            "5000",
            SpecialVarType::Number {
                min: 0,
                max: 100000,
            },
            "Maximum number of history entries",
        ),
        SpecialVariable::new(
            "EDITOR",
            "vi",
            SpecialVarType::String,
            "External editor command",
        ),
        SpecialVariable::new(
            "FORMAT",
            "table",
            SpecialVarType::Enum {
                values: vec![
                    "table".into(),
                    "csv".into(),
                    "json".into(),
                    "vertical".into(),
                    "html".into(),
                ],
            },
            "Default output format",
        ),
        SpecialVariable::new(
            "COMP_KEYWORD_CASE",
            "upper",
            SpecialVarType::Enum {
                values: vec!["upper".into(), "lower".into(), "preserve".into()],
            },
            "Keyword case for completion: upper, lower, preserve",
        ),
        SpecialVariable::new(
            "AUTOCOMMIT",
            "on",
            SpecialVarType::Boolean,
            "Auto-commit mode",
        ),
        SpecialVariable::new(
            "VERBOSITY",
            "default",
            SpecialVarType::Enum {
                values: vec!["default".into(), "terse".into(), "verbose".into()],
            },
            "Error message verbosity: default, terse, verbose",
        ),
    ]
}

#[derive(Debug, Clone)]
pub struct VariableStore {
    user_vars: HashMap<String, String>,
    special_vars: HashMap<String, SpecialVariable>,
    special_values: HashMap<String, String>,
}

impl Default for VariableStore {
    fn default() -> Self {
        Self::new()
    }
}

impl VariableStore {
    pub fn new() -> Self {
        let specials = define_special_variables();
        let mut special_vars = HashMap::new();
        let mut special_values = HashMap::new();

        for sv in specials {
            let default = sv.default_value.clone();
            special_values.insert(sv.name.clone(), default);
            special_vars.insert(sv.name.clone(), sv);
        }

        Self {
            user_vars: HashMap::new(),
            special_vars,
            special_values,
        }
    }

    pub fn set(&mut self, name: String, value: String) -> Result<()> {
        if self.special_vars.contains_key(&name) {
            let sv = self
                .special_vars
                .get(&name)
                .cloned()
                .expect("checked above");
            let validated = sv.validate(&value)?;
            self.special_values.insert(name, validated);
        } else {
            self.user_vars.insert(name, value);
        }
        Ok(())
    }

    pub fn get(&self, name: &str) -> Option<&String> {
        if self.special_values.contains_key(name) {
            self.special_values.get(name)
        } else {
            self.user_vars.get(name)
        }
    }

    pub fn remove(&mut self, name: &str) -> bool {
        if self.special_vars.contains_key(name) {
            if let Some(sv) = self.special_vars.get(name) {
                self.special_values
                    .insert(name.to_string(), sv.default_value.clone());
            }
            true
        } else {
            self.user_vars.remove(name).is_some()
        }
    }

    pub fn is_special(&self, name: &str) -> bool {
        self.special_vars.contains_key(name)
    }

    pub fn user_variables(&self) -> &HashMap<String, String> {
        &self.user_vars
    }

    pub fn special_variables(&self) -> &HashMap<String, SpecialVariable> {
        &self.special_vars
    }

    pub fn special_values(&self) -> &HashMap<String, String> {
        &self.special_values
    }

    pub fn all_variables(&self) -> Vec<(&String, &String)> {
        let mut all: Vec<(&String, &String)> = Vec::new();
        for (k, v) in &self.special_values {
            all.push((k, v));
        }
        for (k, v) in &self.user_vars {
            all.push((k, v));
        }
        all.sort_by(|a, b| a.0.cmp(b.0));
        all
    }

    pub fn get_bool(&self, name: &str) -> bool {
        self.get(name)
            .map(|v| matches!(v.as_str(), "on" | "true" | "yes" | "1"))
            .unwrap_or(false)
    }

    pub fn get_special_var(&self, name: &str) -> Option<&String> {
        self.special_values.get(name)
    }

    pub fn substitute(&self, input: &str) -> Result<String> {
        let mut result = String::with_capacity(input.len());
        let chars: Vec<char> = input.chars().collect();
        let mut i = 0;

        while i < chars.len() {
            if chars[i] == ':' && i + 1 < chars.len() {
                if chars[i + 1] == ':' {
                    result.push(':');
                    i += 2;
                    continue;
                }

                if chars[i + 1] == '\'' {
                    let (replaced, new_i) = self.substitute_quoted(&chars, i + 2, '\'')?;
                    result.push_str(&replaced);
                    i = new_i;
                    continue;
                }

                if chars[i + 1] == '"' {
                    let (replaced, new_i) = self.substitute_quoted(&chars, i + 2, '"')?;
                    result.push_str(&replaced);
                    i = new_i;
                    continue;
                }

                if is_var_start_char(chars[i + 1]) {
                    let (replaced, new_i) = self.substitute_plain(&chars, i + 1)?;
                    result.push_str(&replaced);
                    i = new_i;
                    continue;
                }
            }

            result.push(chars[i]);
            i += 1;
        }

        Ok(result)
    }

    fn substitute_plain(&self, chars: &[char], start: usize) -> Result<(String, usize)> {
        let mut end = start;
        while end < chars.len() && is_var_char(chars[end]) {
            end += 1;
        }

        let var_name: String = chars[start..end].iter().collect();

        if let Some(env_key) = var_name.strip_prefix("ENV_") {
            let value = std::env::var(env_key).map_err(|_| {
                CliError::Other(format!("Undefined environment variable: {}", env_key))
            })?;
            return Ok((value, end));
        }

        let value = self
            .get(&var_name)
            .ok_or_else(|| CliError::Other(format!("Undefined variable: :{}", var_name)))?;

        Ok((value.clone(), end))
    }

    fn substitute_quoted(
        &self,
        chars: &[char],
        start: usize,
        quote: char,
    ) -> Result<(String, usize)> {
        let mut end = start;
        while end < chars.len() && chars[end] != quote {
            end += 1;
        }

        if end >= chars.len() {
            return Err(CliError::Other(
                "Unterminated quoted variable reference".to_string(),
            ));
        }

        let var_name: String = chars[start..end].iter().collect();

        if let Some(env_key) = var_name.strip_prefix("ENV_") {
            let value = std::env::var(env_key).map_err(|_| {
                CliError::Other(format!("Undefined environment variable: {}", env_key))
            })?;
            return Ok((format!("{}{}{}", quote, value, quote), end + 1));
        }

        let value = self
            .get(&var_name)
            .ok_or_else(|| CliError::Other(format!("Undefined variable: :{}", var_name)))?;

        Ok((format!("{}{}{}", quote, value, quote), end + 1))
    }
}

fn is_var_start_char(c: char) -> bool {
    c.is_ascii_alphabetic() || c == '_'
}

fn is_var_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || c == '_'
}
