//! The PlanNode trait is implemented.

use super::plan_node_enum::PlanNodeEnum;
use super::plan_node_traits::PlanNodeClonable;
use crate::query::core::{NodeCategory, NodeType, NodeTypeMapping};

impl NodeType for PlanNodeEnum {
    fn node_type_id(&self) -> &'static str {
        match self {
            PlanNodeEnum::Start(_) => "start",
            PlanNodeEnum::Project(_) => "project",
            PlanNodeEnum::Sort(_) => "sort",
            PlanNodeEnum::Limit(_) => "limit",
            PlanNodeEnum::TopN(_) => "topn",
            PlanNodeEnum::Sample(_) => "sample",
            PlanNodeEnum::InnerJoin(_) => "inner_join",
            PlanNodeEnum::LeftJoin(_) => "left_join",
            PlanNodeEnum::RightJoin(_) => "right_join",
            PlanNodeEnum::CrossJoin(_) => "cross_join",
            PlanNodeEnum::SemiJoin(_) => "semi_join",
            PlanNodeEnum::GetVertices(_) => "get_vertices",
            PlanNodeEnum::GetEdges(_) => "get_edges",
            PlanNodeEnum::GetNeighbors(_) => "get_neighbors",
            PlanNodeEnum::ScanVertices(_) => "scan_vertices",
            PlanNodeEnum::ScanEdges(_) => "scan_edges",
            PlanNodeEnum::EdgeIndexScan(_) => "edge_index_scan",
            PlanNodeEnum::HashInnerJoin(_) => "hash_inner_join",
            PlanNodeEnum::HashLeftJoin(_) => "hash_left_join",
            PlanNodeEnum::FullOuterJoin(_) => "full_outer_join",
            PlanNodeEnum::IndexScan(_) => "index_scan",
            PlanNodeEnum::Expand(_) => "expand",
            PlanNodeEnum::ExpandAll(_) => "expand_all",
            PlanNodeEnum::Traverse(_) => "traverse",
            PlanNodeEnum::AppendVertices(_) => "append_vertices",
            PlanNodeEnum::BiExpand(_) => "bi_expand",
            PlanNodeEnum::BiTraverse(_) => "bi_traverse",
            PlanNodeEnum::Filter(_) => "filter",
            PlanNodeEnum::Aggregate(_) => "aggregate",
            PlanNodeEnum::Argument(_) => "argument",
            PlanNodeEnum::Loop(_) => "loop",
            PlanNodeEnum::PassThrough(_) => "pass_through",
            PlanNodeEnum::Select(_) => "select",
            PlanNodeEnum::BeginTransaction(_) => "begin_transaction",
            PlanNodeEnum::Commit(_) => "commit",
            PlanNodeEnum::Rollback(_) => "rollback",
            PlanNodeEnum::DataCollect(_) => "data_collect",
            PlanNodeEnum::Dedup(_) => "dedup",
            PlanNodeEnum::PatternApply(_) => "pattern_apply",
            PlanNodeEnum::RollUpApply(_) => "rollup_apply",
            PlanNodeEnum::Remove(_) => "remove",
            PlanNodeEnum::Union(_) => "union",
            PlanNodeEnum::Minus(_) => "minus",
            PlanNodeEnum::Intersect(_) => "intersect",
            PlanNodeEnum::Unwind(_) => "unwind",
            PlanNodeEnum::Materialize(_) => "materialize",
            PlanNodeEnum::Assign(_) => "assign",
            PlanNodeEnum::Apply(_) => "apply",
            PlanNodeEnum::MultiShortestPath(_) => "multi_shortest_path",
            PlanNodeEnum::BFSShortest(_) => "bfs_shortest",
            PlanNodeEnum::AllPaths(_) => "all_paths",
            PlanNodeEnum::ShortestPath(_) => "shortest_path",
            PlanNodeEnum::SpaceManage(node) => node.node_type_id(),
            PlanNodeEnum::TagManage(node) => node.node_type_id(),
            PlanNodeEnum::EdgeManage(node) => node.node_type_id(),
            PlanNodeEnum::IndexManage(node) => node.node_type_id(),
            PlanNodeEnum::UserManage(node) => node.node_type_id(),
            PlanNodeEnum::FulltextManage(node) => node.node_type_id(),
            PlanNodeEnum::VectorManage(node) => node.node_type_id(),
            PlanNodeEnum::ShowStats(_) => "show_stats",
            PlanNodeEnum::InsertVertices(_) => "insert_vertices",
            PlanNodeEnum::InsertEdges(_) => "insert_edges",
            PlanNodeEnum::DeleteVertices(_) => "delete_vertices",
            PlanNodeEnum::DeleteEdges(_) => "delete_edges",
            PlanNodeEnum::DeleteTags(_) => "delete_tags",
            PlanNodeEnum::DeleteIndex(_) => "delete_index",
            PlanNodeEnum::PipeDeleteVertices(_) => "pipe_delete_vertices",
            PlanNodeEnum::PipeDeleteEdges(_) => "pipe_delete_edges",
            PlanNodeEnum::Update(_) => "update",
            PlanNodeEnum::UpdateVertices(_) => "update_vertices",
            PlanNodeEnum::UpdateEdges(_) => "update_edges",
            PlanNodeEnum::FulltextSearch(_) => "fulltext_search",
            PlanNodeEnum::FulltextLookup(_) => "fulltext_lookup",
            PlanNodeEnum::MatchFulltext(_) => "match_fulltext",
            #[cfg(feature = "qdrant")]
            PlanNodeEnum::VectorSearch(_) => "vector_search",
            #[cfg(feature = "qdrant")]
            PlanNodeEnum::VectorLookup(_) => "vector_lookup",
            #[cfg(feature = "qdrant")]
            PlanNodeEnum::VectorMatch(_) => "vector_match",
        }
    }

    fn node_type_name(&self) -> &'static str {
        match self {
            PlanNodeEnum::Start(_) => "Start",
            PlanNodeEnum::Project(_) => "Project",
            PlanNodeEnum::Sort(_) => "Sort",
            PlanNodeEnum::Limit(_) => "Limit",
            PlanNodeEnum::TopN(_) => "TopN",
            PlanNodeEnum::Sample(_) => "Sample",
            PlanNodeEnum::InnerJoin(_) => "Inner Join",
            PlanNodeEnum::LeftJoin(_) => "Left Join",
            PlanNodeEnum::RightJoin(_) => "Right Join",
            PlanNodeEnum::CrossJoin(_) => "Cross Join",
            PlanNodeEnum::SemiJoin(_) => "Semi Join",
            PlanNodeEnum::GetVertices(_) => "Get Vertices",
            PlanNodeEnum::GetEdges(_) => "Get Edges",
            PlanNodeEnum::GetNeighbors(_) => "Get Neighbors",
            PlanNodeEnum::ScanVertices(_) => "Scan Vertices",
            PlanNodeEnum::ScanEdges(_) => "Scan Edges",
            PlanNodeEnum::EdgeIndexScan(_) => "Edge Index Scan",
            PlanNodeEnum::HashInnerJoin(_) => "Hash Inner Join",
            PlanNodeEnum::HashLeftJoin(_) => "Hash Left Join",
            PlanNodeEnum::FullOuterJoin(_) => "Full Outer Join",
            PlanNodeEnum::IndexScan(_) => "Index Scan",
            PlanNodeEnum::Expand(_) => "Expand",
            PlanNodeEnum::ExpandAll(_) => "Expand All",
            PlanNodeEnum::Traverse(_) => "Traverse",
            PlanNodeEnum::AppendVertices(_) => "Append Vertices",
            PlanNodeEnum::BiExpand(_) => "BiExpand",
            PlanNodeEnum::BiTraverse(_) => "BiTraverse",
            PlanNodeEnum::Filter(_) => "Filter",
            PlanNodeEnum::Aggregate(_) => "Aggregate",
            PlanNodeEnum::Argument(_) => "Argument",
            PlanNodeEnum::Loop(_) => "Loop",
            PlanNodeEnum::PassThrough(_) => "Pass Through",
            PlanNodeEnum::Select(_) => "Select",
            PlanNodeEnum::BeginTransaction(_) => "Begin Transaction",
            PlanNodeEnum::Commit(_) => "Commit",
            PlanNodeEnum::Rollback(_) => "Rollback",
            PlanNodeEnum::DataCollect(_) => "Data Collect",
            PlanNodeEnum::Dedup(_) => "Dedup",
            PlanNodeEnum::PatternApply(_) => "Pattern Apply",
            PlanNodeEnum::RollUpApply(_) => "RollUp Apply",
            PlanNodeEnum::Remove(_) => "Remove",
            PlanNodeEnum::Union(_) => "Union",
            PlanNodeEnum::Minus(_) => "Minus",
            PlanNodeEnum::Intersect(_) => "Intersect",
            PlanNodeEnum::Unwind(_) => "Unwind",
            PlanNodeEnum::Materialize(_) => "Materialize",
            PlanNodeEnum::Assign(_) => "Assign",
            PlanNodeEnum::Apply(_) => "Apply",
            PlanNodeEnum::MultiShortestPath(_) => "Multi Shortest Path",
            PlanNodeEnum::BFSShortest(_) => "BFS Shortest",
            PlanNodeEnum::AllPaths(_) => "All Paths",
            PlanNodeEnum::ShortestPath(_) => "Shortest Path",
            PlanNodeEnum::SpaceManage(node) => node.node_type_name(),
            PlanNodeEnum::TagManage(node) => node.node_type_name(),
            PlanNodeEnum::EdgeManage(node) => node.node_type_name(),
            PlanNodeEnum::IndexManage(node) => node.node_type_name(),
            PlanNodeEnum::UserManage(node) => node.node_type_name(),
            PlanNodeEnum::FulltextManage(node) => node.node_type_name(),
            PlanNodeEnum::VectorManage(node) => node.node_type_name(),
            PlanNodeEnum::ShowStats(_) => "Show Stats",
            PlanNodeEnum::InsertVertices(_) => "Insert Vertices",
            PlanNodeEnum::InsertEdges(_) => "Insert Edges",
            PlanNodeEnum::DeleteVertices(_) => "Delete Vertices",
            PlanNodeEnum::DeleteEdges(_) => "Delete Edges",
            PlanNodeEnum::DeleteTags(_) => "Delete Tags",
            PlanNodeEnum::DeleteIndex(_) => "Delete Index",
            PlanNodeEnum::PipeDeleteVertices(_) => "Pipe Delete Vertices",
            PlanNodeEnum::PipeDeleteEdges(_) => "Pipe Delete Edges",
            PlanNodeEnum::Update(_) => "Update",
            PlanNodeEnum::UpdateVertices(_) => "Update Vertices",
            PlanNodeEnum::UpdateEdges(_) => "Update Edges",
            PlanNodeEnum::FulltextSearch(_) => "Fulltext Search",
            PlanNodeEnum::FulltextLookup(_) => "Fulltext Lookup",
            PlanNodeEnum::MatchFulltext(_) => "Match Fulltext",
            #[cfg(feature = "qdrant")]
            PlanNodeEnum::VectorSearch(_) => "Vector Search",
            #[cfg(feature = "qdrant")]
            PlanNodeEnum::VectorLookup(_) => "Vector Lookup",
            #[cfg(feature = "qdrant")]
            PlanNodeEnum::VectorMatch(_) => "Vector Match",
        }
    }

    fn category(&self) -> NodeCategory {
        match self {
            PlanNodeEnum::Start(_) => NodeCategory::Scan,
            PlanNodeEnum::Project(_) => NodeCategory::Project,
            PlanNodeEnum::Sort(_) => NodeCategory::Sort,
            PlanNodeEnum::Limit(_) => NodeCategory::Sort,
            PlanNodeEnum::TopN(_) => NodeCategory::Sort,
            PlanNodeEnum::Sample(_) => NodeCategory::Other,
            PlanNodeEnum::InnerJoin(_) => NodeCategory::Join,
            PlanNodeEnum::LeftJoin(_) => NodeCategory::Join,
            PlanNodeEnum::RightJoin(_) => NodeCategory::Join,
            PlanNodeEnum::CrossJoin(_) => NodeCategory::Join,
            PlanNodeEnum::SemiJoin(_) => NodeCategory::Join,
            PlanNodeEnum::GetVertices(_) => NodeCategory::Scan,
            PlanNodeEnum::GetEdges(_) => NodeCategory::Scan,
            PlanNodeEnum::GetNeighbors(_) => NodeCategory::Scan,
            PlanNodeEnum::ScanVertices(_) => NodeCategory::Scan,
            PlanNodeEnum::ScanEdges(_) => NodeCategory::Scan,
            PlanNodeEnum::EdgeIndexScan(_) => NodeCategory::Scan,
            PlanNodeEnum::HashInnerJoin(_) => NodeCategory::Join,
            PlanNodeEnum::HashLeftJoin(_) => NodeCategory::Join,
            PlanNodeEnum::FullOuterJoin(_) => NodeCategory::Join,
            PlanNodeEnum::IndexScan(_) => NodeCategory::Scan,
            PlanNodeEnum::Expand(_) => NodeCategory::Traversal,
            PlanNodeEnum::ExpandAll(_) => NodeCategory::Traversal,
            PlanNodeEnum::Traverse(_) => NodeCategory::Traversal,
            PlanNodeEnum::AppendVertices(_) => NodeCategory::Traversal,
            PlanNodeEnum::BiExpand(_) => NodeCategory::Traversal,
            PlanNodeEnum::BiTraverse(_) => NodeCategory::Traversal,
            PlanNodeEnum::Filter(_) => NodeCategory::Filter,
            PlanNodeEnum::Aggregate(_) => NodeCategory::Aggregate,
            PlanNodeEnum::Argument(_) => NodeCategory::Control,
            PlanNodeEnum::Loop(_) => NodeCategory::Control,
            PlanNodeEnum::PassThrough(_) => NodeCategory::Control,
            PlanNodeEnum::Select(_) => NodeCategory::Control,
            PlanNodeEnum::BeginTransaction(_) => NodeCategory::Control,
            PlanNodeEnum::Commit(_) => NodeCategory::Control,
            PlanNodeEnum::Rollback(_) => NodeCategory::Control,
            PlanNodeEnum::DataCollect(_) => NodeCategory::DataCollect,
            PlanNodeEnum::Dedup(_) => NodeCategory::Aggregate,
            PlanNodeEnum::PatternApply(_) => NodeCategory::DataCollect,
            PlanNodeEnum::RollUpApply(_) => NodeCategory::DataCollect,
            PlanNodeEnum::Remove(_) => NodeCategory::DataCollect,
            PlanNodeEnum::Union(_) => NodeCategory::SetOp,
            PlanNodeEnum::Minus(_) => NodeCategory::SetOp,
            PlanNodeEnum::Intersect(_) => NodeCategory::SetOp,
            PlanNodeEnum::Unwind(_) => NodeCategory::DataCollect,
            PlanNodeEnum::Materialize(_) => NodeCategory::DataCollect,
            PlanNodeEnum::Assign(_) => NodeCategory::DataCollect,
            PlanNodeEnum::Apply(_) => NodeCategory::DataCollect,
            PlanNodeEnum::MultiShortestPath(_) => NodeCategory::Path,
            PlanNodeEnum::BFSShortest(_) => NodeCategory::Path,
            PlanNodeEnum::AllPaths(_) => NodeCategory::Path,
            PlanNodeEnum::ShortestPath(_) => NodeCategory::Path,
            PlanNodeEnum::SpaceManage(_) => NodeCategory::Admin,
            PlanNodeEnum::TagManage(_) => NodeCategory::Admin,
            PlanNodeEnum::EdgeManage(_) => NodeCategory::Admin,
            PlanNodeEnum::IndexManage(_) => NodeCategory::Admin,
            PlanNodeEnum::UserManage(_) => NodeCategory::Admin,
            PlanNodeEnum::FulltextManage(_) => NodeCategory::Admin,
            PlanNodeEnum::VectorManage(_) => NodeCategory::Admin,
            PlanNodeEnum::ShowStats(_) => NodeCategory::Admin,
            PlanNodeEnum::InsertVertices(_) => NodeCategory::Admin,
            PlanNodeEnum::InsertEdges(_) => NodeCategory::Admin,
            PlanNodeEnum::DeleteVertices(_) => NodeCategory::Admin,
            PlanNodeEnum::DeleteEdges(_) => NodeCategory::Admin,
            PlanNodeEnum::DeleteTags(_) => NodeCategory::Admin,
            PlanNodeEnum::DeleteIndex(_) => NodeCategory::Admin,
            PlanNodeEnum::PipeDeleteVertices(_) => NodeCategory::Admin,
            PlanNodeEnum::PipeDeleteEdges(_) => NodeCategory::Admin,
            PlanNodeEnum::Update(_) => NodeCategory::Admin,
            PlanNodeEnum::UpdateVertices(_) => NodeCategory::Admin,
            PlanNodeEnum::UpdateEdges(_) => NodeCategory::Admin,
            PlanNodeEnum::FulltextSearch(_) => NodeCategory::DataAccess,
            PlanNodeEnum::FulltextLookup(_) => NodeCategory::DataAccess,
            PlanNodeEnum::MatchFulltext(_) => NodeCategory::DataAccess,
            #[cfg(feature = "qdrant")]
            PlanNodeEnum::VectorSearch(_) => NodeCategory::DataAccess,
            #[cfg(feature = "qdrant")]
            PlanNodeEnum::VectorLookup(_) => NodeCategory::DataAccess,
            #[cfg(feature = "qdrant")]
            PlanNodeEnum::VectorMatch(_) => NodeCategory::DataAccess,
        }
    }
}

impl NodeTypeMapping for PlanNodeEnum {
    fn corresponding_executor_type(&self) -> Option<&'static str> {
        match self {
            PlanNodeEnum::Start(_) => Some("start"),
            PlanNodeEnum::Project(_) => Some("project"),
            PlanNodeEnum::Sort(_) => Some("sort"),
            PlanNodeEnum::Limit(_) => Some("limit"),
            PlanNodeEnum::TopN(_) => Some("topn"),
            PlanNodeEnum::Sample(_) => Some("sample"),
            PlanNodeEnum::InnerJoin(_) => Some("inner_join"),
            PlanNodeEnum::LeftJoin(_) => Some("left_join"),
            PlanNodeEnum::RightJoin(_) => Some("right_join"),
            PlanNodeEnum::CrossJoin(_) => Some("cross_join"),
            PlanNodeEnum::SemiJoin(_) => Some("semi_join"),
            PlanNodeEnum::GetVertices(_) => Some("get_vertices"),
            PlanNodeEnum::GetEdges(_) => Some("get_edges"),
            PlanNodeEnum::GetNeighbors(_) => Some("get_neighbors"),
            PlanNodeEnum::ScanVertices(_) => Some("scan_vertices"),
            PlanNodeEnum::ScanEdges(_) => Some("scan_edges"),
            PlanNodeEnum::EdgeIndexScan(_) => Some("edge_index_scan"),
            PlanNodeEnum::HashInnerJoin(_) => Some("hash_inner_join"),
            PlanNodeEnum::HashLeftJoin(_) => Some("hash_left_join"),
            PlanNodeEnum::FullOuterJoin(_) => Some("full_outer_join"),
            PlanNodeEnum::IndexScan(_) => Some("index_scan"),
            PlanNodeEnum::Expand(_) => Some("expand"),
            PlanNodeEnum::ExpandAll(_) => Some("expand_all"),
            PlanNodeEnum::Traverse(_) => Some("traverse"),
            PlanNodeEnum::AppendVertices(_) => Some("append_vertices"),
            PlanNodeEnum::BiExpand(_) => Some("bi_expand"),
            PlanNodeEnum::BiTraverse(_) => Some("bi_traverse"),
            PlanNodeEnum::Filter(_) => Some("filter"),
            PlanNodeEnum::Aggregate(_) => Some("aggregate"),
            PlanNodeEnum::Argument(_) => Some("argument"),
            PlanNodeEnum::Loop(_) => Some("loop"),
            PlanNodeEnum::PassThrough(_) => Some("pass_through"),
            PlanNodeEnum::Select(_) => Some("select"),
            PlanNodeEnum::BeginTransaction(_) => Some("begin_transaction"),
            PlanNodeEnum::Commit(_) => Some("commit"),
            PlanNodeEnum::Rollback(_) => Some("rollback"),
            PlanNodeEnum::DataCollect(_) => Some("data_collect"),
            PlanNodeEnum::Dedup(_) => Some("dedup"),
            PlanNodeEnum::PatternApply(_) => Some("pattern_apply"),
            PlanNodeEnum::RollUpApply(_) => Some("rollup_apply"),
            PlanNodeEnum::Remove(_) => Some("remove"),
            PlanNodeEnum::Union(_) => Some("union"),
            PlanNodeEnum::Minus(_) => Some("minus"),
            PlanNodeEnum::Intersect(_) => Some("intersect"),
            PlanNodeEnum::Unwind(_) => Some("unwind"),
            PlanNodeEnum::Materialize(_) => Some("materialize"),
            PlanNodeEnum::Assign(_) => Some("assign"),
            PlanNodeEnum::Apply(_) => Some("apply"),
            PlanNodeEnum::MultiShortestPath(_) => Some("multi_shortest_path"),
            PlanNodeEnum::BFSShortest(_) => Some("bfs_shortest"),
            PlanNodeEnum::AllPaths(_) => Some("all_paths"),
            PlanNodeEnum::ShortestPath(_) => Some("shortest_path"),
            PlanNodeEnum::SpaceManage(node) => node.corresponding_executor_type(),
            PlanNodeEnum::TagManage(node) => node.corresponding_executor_type(),
            PlanNodeEnum::EdgeManage(node) => node.corresponding_executor_type(),
            PlanNodeEnum::IndexManage(node) => node.corresponding_executor_type(),
            PlanNodeEnum::UserManage(node) => node.corresponding_executor_type(),
            PlanNodeEnum::FulltextManage(node) => node.corresponding_executor_type(),
            PlanNodeEnum::VectorManage(node) => node.corresponding_executor_type(),
            PlanNodeEnum::ShowStats(_) => Some("show_stats"),
            PlanNodeEnum::InsertVertices(_) => Some("insert_vertices"),
            PlanNodeEnum::InsertEdges(_) => Some("insert_edges"),
            PlanNodeEnum::DeleteVertices(_) => Some("delete_vertices"),
            PlanNodeEnum::DeleteEdges(_) => Some("delete_edges"),
            PlanNodeEnum::DeleteTags(_) => Some("delete_tags"),
            PlanNodeEnum::DeleteIndex(_) => Some("delete_index"),
            PlanNodeEnum::PipeDeleteVertices(_) => Some("pipe_delete_vertices"),
            PlanNodeEnum::PipeDeleteEdges(_) => Some("pipe_delete_edges"),
            PlanNodeEnum::Update(_) => Some("update"),
            PlanNodeEnum::UpdateVertices(_) => Some("update_vertices"),
            PlanNodeEnum::UpdateEdges(_) => Some("update_edges"),
            PlanNodeEnum::FulltextSearch(_) => Some("fulltext_search"),
            PlanNodeEnum::FulltextLookup(_) => Some("fulltext_lookup"),
            PlanNodeEnum::MatchFulltext(_) => Some("match_fulltext"),
            #[cfg(feature = "qdrant")]
            PlanNodeEnum::VectorSearch(_) => Some("vector_search"),
            #[cfg(feature = "qdrant")]
            PlanNodeEnum::VectorLookup(_) => Some("vector_lookup"),
            #[cfg(feature = "qdrant")]
            PlanNodeEnum::VectorMatch(_) => Some("vector_match"),
        }
    }
}

impl PlanNodeClonable for PlanNodeEnum {
    fn clone_plan_node(&self) -> PlanNodeEnum {
        self.clone()
    }

    fn clone_with_new_id(&self, _new_id: i64) -> PlanNodeEnum {
        self.clone()
    }
}
