#ifndef LINKRS_H
#define LINKRS_H

/* Generated by cbindgen from crates/linkrs-api. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Hook type constants
 */
#define LINKRS_HOOK_INSERT 1

#define LINKRS_HOOK_UPDATE 2

#define LINKRS_HOOK_DELETE 3

/**
 * Error code
 */
typedef enum linkrs_error_code_t {
  /**
   * Success
   */
  LINKRS_OK = 0,
  /**
   * Common errors
   */
  LINKRS_ERROR = 1,
  /**
   * Internal error
   */
  LINKRS_INTERNAL = 2,
  /**
   * The permission was denied.
   */
  LINKRS_PERM = 3,
  /**
   * The operation was terminated.
   */
  LINKRS_ABORT = 4,
  /**
   * The database is busy.
   */
  LINKRS_BUSY = 5,
  /**
   * The database is locked.
   */
  LINKRS_LOCKED = 6,
  /**
   * Insufficient memory
   */
  LINKRS_NOMEM = 7,
  /**
   * Read-only
   */
  LINKRS_READONLY = 8,
  /**
   * The operation was interrupted.
   */
  LINKRS_INTERRUPT = 9,
  /**
   * IO error
   */
  LINKRS_IOERR = 10,
  /**
   * Data corruption
   */
  LINKRS_CORRUPT = 11,
  /**
   * Nothing was found.
   */
  LINKRS_NOTFOUND = 12,
  /**
   * The disk is full.
   */
  LINKRS_FULL = 13,
  /**
   * Unable to open.
   */
  LINKRS_CANTOPEN = 14,
  /**
   * Protocol error
   */
  LINKRS_PROTOCOL = 15,
  /**
   * Pattern error
   */
  LINKRS_SCHEMA = 16,
  /**
   * The data volume is too large.
   */
  LINKRS_TOOBIG = 17,
  /**
   * Violation of constraints
   */
  LINKRS_CONSTRAINT = 18,
  /**
   * Type mismatch.
   */
  LINKRS_MISMATCH = 19,
  /**
   * Misuse
   */
  LINKRS_MISUSE = 20,
  /**
   * Out of range
   */
  LINKRS_RANGE = 21,
  /**
   * Not implemented
   */
  LINKRS_NOT_IMPLEMENTED = 22,
} linkrs_error_code_t;

/**
 * Extended Error Code
 */
typedef enum linkrs_extended_error_code_t {
  /**
   * No extension error
   */
  LINKRS_EXTENDED_NONE = 0,
  LINKRS_ERROR_SYNTAX = 1000,
  LINKRS_ERROR_SEMANTIC = 1001,
  LINKRS_ERROR_UNEXPECTED_TOKEN = 1002,
  LINKRS_ERROR_UNTERMINATED_LITERAL = 1003,
  LINKRS_ERROR_TYPE_MISMATCH = 1100,
  LINKRS_ERROR_DIVISION_BY_ZERO = 1101,
  LINKRS_ERROR_OUT_OF_RANGE = 1102,
  LINKRS_ERROR_DUPLICATE_KEY = 1200,
  LINKRS_ERROR_FOREIGN_KEY = 1201,
  LINKRS_ERROR_NOT_NULL = 1202,
  LINKRS_ERROR_UNIQUE = 1203,
  LINKRS_ERROR_CHECK = 1204,
  LINKRS_ERROR_CONNECTION_LOST = 1300,
  LINKRS_ERROR_DEADLOCK = 1301,
  LINKRS_ERROR_LOCK_TIMEOUT = 1302,
  LINKRS_ERROR_CONFLICT = 1303,
  LINKRS_ERROR_NOT_OWNER = 1304,
  LINKRS_ERROR_ALREADY_COMPLETED = 1305,
  LINKRS_ERROR_RECOVERY_REQUIRED = 1306,
  LINKRS_ERROR_INVALID_VERTEX = 1400,
  LINKRS_ERROR_INVALID_EDGE = 1401,
  LINKRS_ERROR_PATH_NOT_FOUND = 1402,
  LINKRS_ERROR_INTERNAL = 1500,
} linkrs_extended_error_code_t;

/**
 * Tag describing which payload a value carries.
 */
typedef enum linkrs_value_type_t {
  /**
   * Null / empty value
   */
  LINKRS_NULL = 0,
  /**
   * Boolean
   */
  LINKRS_BOOL = 1,
  /**
   * 64-bit signed integer
   */
  LINKRS_INT = 2,
  /**
   * Double-precision floating point
   */
  LINKRS_FLOAT = 3,
  /**
   * UTF-8 string
   */
  LINKRS_STRING = 4,
  /**
   * List
   */
  LINKRS_LIST = 5,
  /**
   * Map / dictionary
   */
  LINKRS_MAP = 6,
  /**
   * Vertex
   */
  LINKRS_VERTEX = 7,
  /**
   * Edge
   */
  LINKRS_EDGE = 8,
  /**
   * Path
   */
  LINKRS_PATH = 9,
  /**
   * Binary blob
   */
  LINKRS_BLOB = 10,
} linkrs_value_type_t;

/**
 * Session handles (opaque pointers)
 */
typedef struct linkrs_session_t {
  uint8_t _dummy;
} linkrs_session_t;

/**
 * Batch operation handles (opaque pointers)
 */
typedef struct linkrs_batch_t {
  uint8_t _dummy;
} linkrs_batch_t;

/**
 * Borrowed string view; the data pointer is not owned by this struct.
 */
typedef struct linkrs_string_t {
  /**
   * Pointer to UTF-8 bytes (not null-terminated; length lives in `len`)
   */
  const char *data;
  /**
   * Length in bytes
   */
  uintptr_t len;
} linkrs_string_t;

/**
 * Borrowed binary blob view; the data pointer is not owned by this struct.
 */
typedef struct linkrs_blob_t {
  /**
   * Pointer to the first byte
   */
  const uint8_t *data;
  /**
   * Length in bytes
   */
  uintptr_t len;
} linkrs_blob_t;

/**
 * Payload union; active member is selected by the value type tag.
 */
typedef union linkrs_value_data_t {
  /**
   * Boolean payload
   */
  bool boolean;
  /**
   * Integer payload
   */
  int64_t integer;
  /**
   * Floating-point payload
   */
  double floating;
  /**
   * String payload (borrowed view)
   */
  struct linkrs_string_t string;
  /**
   * Binary blob payload (borrowed view)
   */
  struct linkrs_blob_t blob;
  /**
   * Opaque pointer payload
   */
  void *ptr;
} linkrs_value_data_t;

/**
 * Value: a type tag plus its payload.
 */
typedef struct linkrs_value_t {
  /**
   * Type tag of this value
   */
  enum linkrs_value_type_t type_;
  /**
   * Payload of this value
   */
  union linkrs_value_data_t data;
} linkrs_value_t;

/**
 * Busy handler handle (opaque pointer).
 *
 * Created by `linkrs_busy_handler_create`, released with
 * `linkrs_busy_handler_free`.
 */
typedef struct linkrs_busy_handler_t {
  uint8_t _dummy;
} linkrs_busy_handler_t;

/**
 * Database configuration handle (opaque pointer).
 *
 * The handle owns a `DatabaseConfig` and must be created with
 * `linkrs_config_new/_file/_memory`, tuned with the `linkrs_config_set_*`
 * setters, consumed with `linkrs_open_with_config`, and released with
 * `linkrs_config_free`. It is opaque on purpose: pattern matches the other
 * handle types in this module.
 */
typedef struct linkrs_config_t {
  uint8_t _dummy;
} linkrs_config_t;

/**
 * Database handle (opaque pointer)
 *
 * The `_dummy` member gives the type a real size in C: an empty struct is
 * not valid C11 and MSVC rejects it (C2016).
 */
typedef struct linkrs_t {
  uint8_t _dummy;
} linkrs_t;

/**
 * Function execution context (opaque pointer).
 *
 * The context is passed to registered callbacks as a borrowed pointer to the
 * query engine's `CFunctionContext`; all access goes through the
 * `linkrs_context_*` functions below, so the layout stays private to C.
 */
typedef struct linkrs_context_t {
  uint8_t _dummy;
} linkrs_context_t;

/**
 * Scalar function callback type
 */
typedef void (*linkrs_scalar_function_callback)(struct linkrs_context_t *context,
                                                int argc,
                                                struct linkrs_value_t *argv);

/**
 * Function destruction callback type
 */
typedef void (*linkrs_function_destroy_callback)(void *user_data);

/**
 * Aggregation function step callback type
 */
typedef void (*linkrs_aggregate_step_callback)(struct linkrs_context_t *context,
                                               int argc,
                                               struct linkrs_value_t *argv);

/**
 * The final callback type of the aggregate function
 */
typedef void (*linkrs_aggregate_final_callback)(struct linkrs_context_t *context);

/**
 * C representation of a migration report.
 */
typedef struct linkrs_migration_report_t {
  uint8_t success;
  uint64_t steps_completed;
  uint64_t rows_migrated;
  /**
   * Null-terminated JSON string of errors array; caller must free via `linkrs_free_string`.
   */
  char *errors_json;
} linkrs_migration_report_t;

/**
 * Result set handle (opaque pointer)
 */
typedef struct linkrs_result_t {
  uint8_t _dummy;
} linkrs_result_t;

/**
 * SQL Trace Callback Types
 */
typedef void (*linkrs_trace_callback)(const char *sql, void *user_data);

/**
 * Hook Callback Types
 */
typedef int (*linkrs_commit_hook_callback)(void *user_data);

typedef void (*linkrs_rollback_hook_callback)(void *user_data);

typedef void (*linkrs_update_hook_callback)(void *user_data,
                                            int operation,
                                            const char *database,
                                            const char *table,
                                            int64_t rowid);

/**
 * Session statistics structure
 */
typedef struct linkrs_session_statistics_t {
  /**
   * Number of rows affected by the last operation
   */
  uint64_t last_changes;
  /**
   * Total number of rows affected
   */
  uint64_t total_changes;
  /**
   * ID of the last inserted vertex (0 if none)
   */
  uint64_t last_insert_vertex_id;
  /**
   * ID of the last inserted edge (0 if none)
   */
  uint64_t last_insert_edge_id;
} linkrs_session_statistics_t;

/**
 * Transaction handles (opaque pointers)
 */
typedef struct linkrs_txn_t {
  uint8_t _dummy;
} linkrs_txn_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a batch inserter
 *
 * # Parameters
 * - `session`: session handle
 * - `batch_size`: batch size
 * - `batch`: output parameter, batch operation handle
 *
 * # Returns
 * Success: LINKRS_OK
 * Failure: Error code
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `batch_size` must be a positive integer (if <= 0, defaults to 100)
 * - `batch` must be a valid pointer to store the batch handle
 * - The created batch handle holds a session pointer but does not own the session
 * - The caller must ensure the session is not closed before the batch handle is freed
 * - The caller is responsible for freeing the batch handle using `linkrs_batch_free` when done
 */
int linkrs_batch_inserter_create(struct linkrs_session_t *session,
                                 int batch_size,
                                 struct linkrs_batch_t **batch);

/**
 * Free batch operation handle
 *
 * # Parameters
 * - `batch`: batch operation handle
 *
 * # Safety
 * - `batch` must be a valid batch handle created by `linkrs_batch_inserter_create`
 * - `batch` can be null (in which case this function does nothing)
 * - After calling this function, the handle is invalid and must not be used again
 */
int linkrs_batch_free(struct linkrs_batch_t *batch);

/**
 * Add a vertex to the batch
 *
 * # Parameters
 * - `batch`: batch operation handle
 * - `vid`: vertex ID
 * - `tags`: single tag name (exactly one label is required)
 *
 * # Returns
 * Success: LINKRS_OK
 * Failure: Error code
 *
 * # Safety
 * - `batch` must be a valid batch handle
 * - `vid` must be a valid pointer to a linkrs_value_t
 * - `tags` must be a non-null single tag name (null, empty, or
 *   multi-tag comma-separated values are rejected)
 */
int linkrs_batch_add_vertex(struct linkrs_batch_t *batch,
                            const struct linkrs_value_t *vid,
                            const char *tags);

/**
 * Add an edge to the batch
 *
 * # Parameters
 * - `batch`: batch operation handle
 * - `src_vid`: source vertex ID
 * - `dst_vid`: destination vertex ID
 * - `edge_type`: edge type
 *
 * # Returns
 * Success: LINKRS_OK
 * Failure: Error code
 *
 * # Safety
 * - `batch` must be a valid batch handle
 * - `src_vid` and `dst_vid` must be valid pointers to linkrs_value_t
 * - `edge_type` must be a valid null-terminated UTF-8 string
 */
int linkrs_batch_add_edge(struct linkrs_batch_t *batch,
                          const struct linkrs_value_t *src_vid,
                          const struct linkrs_value_t *dst_vid,
                          const char *edge_type);

/**
 * Execute batch operation (flush all buffered data)
 *
 * # Parameters
 * - `batch`: batch operation handle
 *
 * # Returns
 * Success: LINKRS_OK
 * Failure: Error code
 *
 * # Safety
 * - `batch` must be a valid batch handle
 */
int linkrs_batch_execute(struct linkrs_batch_t *batch);

/**
 * Get the number of vertices inserted
 *
 * # Parameters
 * - `batch`: batch operation handle
 * - `count`: output parameter
 *
 * # Returns
 * Success: LINKRS_OK
 * Failure: Error code
 *
 * # Safety
 * - `batch` must be a valid batch handle
 * - `count` must be a valid pointer
 */
int linkrs_batch_vertices_inserted(struct linkrs_batch_t *batch, int *count);

/**
 * Get the number of edges inserted
 *
 * # Parameters
 * - `batch`: batch operation handle
 * - `count`: output parameter
 *
 * # Returns
 * Success: LINKRS_OK
 * Failure: Error code
 *
 * # Safety
 * - `batch` must be a valid batch handle
 * - `count` must be a valid pointer
 */
int linkrs_batch_edges_inserted(struct linkrs_batch_t *batch, int *count);

/**
 * Get the number of buffered vertices
 *
 * # Safety
 * - `batch` must be a valid batch handle or null
 *
 * # Returns
 * - Number of buffered vertices, or -1 if batch is null
 */
int linkrs_batch_buffered_vertices(struct linkrs_batch_t *batch);

/**
 * Get the number of buffered edges
 *
 * # Safety
 * - `batch` must be a valid batch handle or null
 *
 * # Returns
 * - Number of buffered edges, or -1 if batch is null
 */
int linkrs_batch_buffered_edges(struct linkrs_batch_t *batch);

/**
 * Create a new busy handler
 *
 * # Arguments
 * - `timeout_ms`: Timeout in milliseconds, 0 means no wait
 *
 * # Returns
 * - Busy handler handle
 *
 * # Memory Management
 * The returned handler must be freed using `linkrs_busy_handler_free` when done
 *
 * # Safety
 * This function uses FFI and returns a raw pointer. The returned pointer must be freed
 * using `linkrs_busy_handler_free` to avoid memory leaks.
 */
struct linkrs_busy_handler_t *linkrs_busy_handler_create(int timeout_ms);

/**
 * Free busy handler
 *
 * # Arguments
 * - `handler`: Busy handler handle
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `handler` must be a valid busy handler handle created by `linkrs_busy_handler_create`
 */
int linkrs_busy_handler_free(struct linkrs_busy_handler_t *handler);

/**
 * Handle busy condition
 *
 * Returns 1 to continue waiting, 0 to abort (timeout)
 *
 * # Arguments
 * - `handler`: Busy handler handle
 *
 * # Returns
 * - 1: Continue waiting
 * - 0: Timeout or abort
 *
 * # Safety
 * - `handler` must be a valid busy handler handle
 */
int linkrs_busy_handler_handle(struct linkrs_busy_handler_t *handler);

/**
 * Check if timeout has expired
 *
 * # Arguments
 * - `handler`: Busy handler handle
 *
 * # Returns
 * - 1: Timeout expired
 * - 0: Not timeout
 *
 * # Safety
 * - `handler` must be a valid busy handler handle
 */
int linkrs_busy_handler_is_timeout(struct linkrs_busy_handler_t *handler);

/**
 * Get current retry count
 *
 * # Arguments
 * - `handler`: Busy handler handle
 *
 * # Returns
 * - Retry count, returns 0 on error
 *
 * # Safety
 * - `handler` must be a valid busy handler handle
 */
uint32_t linkrs_busy_handler_retry_count(struct linkrs_busy_handler_t *handler);

/**
 * Get elapsed time in milliseconds
 *
 * # Arguments
 * - `handler`: Busy handler handle
 *
 * # Returns
 * - Elapsed time in milliseconds, returns 0 on error
 *
 * # Safety
 * - `handler` must be a valid busy handler handle
 */
uint64_t linkrs_busy_handler_elapsed_ms(struct linkrs_busy_handler_t *handler);

/**
 * Reset busy handler state
 *
 * # Arguments
 * - `handler`: Busy handler handle
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `handler` must be a valid busy handler handle
 */
int linkrs_busy_handler_reset(struct linkrs_busy_handler_t *handler);

/**
 * Create a new configuration (default configuration)
 *
 * # Returns
 * - Configuration handle
 *
 * # Memory Management
 * The returned configuration must be freed using `linkrs_config_free` when done
 *
 * # Safety
 * This function uses FFI and returns a raw pointer. The returned pointer must be freed
 * using `linkrs_config_free` to avoid memory leaks.
 */
struct linkrs_config_t *linkrs_config_new(void);

/**
 * Create a file database configuration
 *
 * # Arguments
 * - `path`: Database file path (UTF-8 encoded)
 *
 * # Returns
 * - Configuration handle
 *
 * # Safety
 * - `path` must be a valid pointer to a null-terminated UTF-8 string
 * - The returned configuration must be freed using `linkrs_config_free` when done
 */
struct linkrs_config_t *linkrs_config_file(const char *path);

/**
 * Create an in-memory database configuration
 *
 * # Returns
 * - Configuration handle
 *
 * # Memory Management
 * The returned configuration must be freed using `linkrs_config_free` when done
 *
 * # Safety
 * This function uses FFI and returns a raw pointer. The returned pointer must be freed
 * using `linkrs_config_free` to avoid memory leaks.
 */
struct linkrs_config_t *linkrs_config_memory(void);

/**
 * Free configuration handle
 *
 * # Arguments
 * - `config`: Configuration handle
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `config` must be a valid configuration handle created by linkrs_config_new,
 *   linkrs_config_file, or linkrs_config_memory
 */
int linkrs_config_free(struct linkrs_config_t *config);

/**
 * Set cache size
 *
 * # Arguments
 * - `config`: Configuration handle
 * - `size_mb`: Cache size in MB
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `config` must be a valid configuration handle
 */
int linkrs_config_set_cache_size(struct linkrs_config_t *config, int size_mb);

/**
 * Set timeout
 *
 * # Arguments
 * - `config`: Configuration handle
 * - `timeout_ms`: Timeout in milliseconds
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `config` must be a valid configuration handle
 */
int linkrs_config_set_timeout(struct linkrs_config_t *config, int timeout_ms);

/**
 * Set read-only mode
 *
 * # Arguments
 * - `config`: Configuration handle
 * - `read_only`: Read-only flag
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `config` must be a valid configuration handle
 */
int linkrs_config_set_read_only(struct linkrs_config_t *config, int read_only);

/**
 * Set create-if-missing flag
 *
 * # Arguments
 * - `config`: Configuration handle
 * - `create`: Create-if-missing flag
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `config` must be a valid configuration handle
 */
int linkrs_config_set_create_if_missing(struct linkrs_config_t *config, int create);

/**
 * Set WAL (Write-Ahead Logging) enabled
 *
 * # Arguments
 * - `config`: Configuration handle
 * - `enable`: Enable flag
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `config` must be a valid configuration handle
 */
int linkrs_config_set_enable_wal(struct linkrs_config_t *config, int enable);

/**
 * Set the synchronization mode (mirrors `SyncMode`).
 *
 * # Arguments
 * - `config`: Configuration handle
 * - `mode`: 0 = Full (every write synced), 1 = Normal (default), 2 = Off
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: LINKRS_MISUSE for null handles or out-of-range modes
 *
 * # Safety
 * - `config` must be a valid configuration handle
 */
int linkrs_config_set_sync_mode(struct linkrs_config_t *config, int mode);

/**
 * Open database
 *
 * # Arguments
 * - `path`: Database file path (UTF-8 encoded)
 * - `db`: Output parameter, database handle
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `path` must be a valid pointer to a null-terminated UTF-8 string
 * - `db` must be a valid pointer to store the database handle
 * - The caller is responsible for closing the database using `linkrs_close` when done
 * - The database handle must not be used after closing
 */
int linkrs_open(const char *path, struct linkrs_t **db);

/**
 * Open the database with a configuration handle.
 *
 * The configuration handle stays valid after the call: it can be reused
 * and must still be released with `linkrs_config_free`.
 *
 * # Arguments
 * - `config`: Configuration handle from `linkrs_config_new/_file/_memory`
 * - `db`: Output parameter, database handle
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `config` must be a valid configuration handle
 * - `db` must be a valid pointer to store the database handle
 * - The caller is responsible for closing the database using `linkrs_close` when done
 */
int linkrs_open_with_config(struct linkrs_config_t *config, struct linkrs_t **db);

/**
 * Closing the database
 *
 * # Arguments
 * - `db`: Database handle
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `db` must be a valid database handle created by `linkrs_open` or `linkrs_open_with_config`
 * - After calling this function, the database handle becomes invalid and must not be used
 * - All sessions associated with this database must be closed before calling this function
 */
int linkrs_close(struct linkrs_t *db);

/**
 * Get Error Code
 *
 * # Arguments
 * - `db`: Database handle
 *
 * # Returns
 * - Error code, returns LINKRS_OK if no error
 *
 * # Safety
 * - `db` must be a valid database handle created by `linkrs_open` or `linkrs_open_with_config`
 */
int linkrs_errcode(struct linkrs_t *db);

/**
 * Getting the library version
 *
 * # Back
 * - revision string (computing)
 */
const char *linkrs_libversion(void);

/**
 * Release strings (strings allocated by Linkrs)
 *
 * # Arguments
 * - `str`: String pointer
 *
 * # Safety
 * - `str` must be a valid pointer to a string allocated by Linkrs
 * - After calling this function, the pointer becomes invalid and must not be used
 * - This function should only be called on strings that were allocated by Linkrs C API functions
 */
void linkrs_free_string(char *str);

/**
 * Freeing memory (memory allocated by Linkrs)
 *
 * # Arguments
 * - `ptr`: Memory pointer
 *
 * # Safety
 * - `ptr` must be a valid pointer to memory allocated by Linkrs
 * - After calling this function, the pointer becomes invalid and must not be used
 * - This function should only be called on memory that was allocated by Linkrs C API functions
 */
void linkrs_free(void *ptr);

/**
 * Retrieve the last error message (thread-safe).
 *
 * # Arguments
 * - `msg`: Output buffer
 * - `len`: Buffer length
 *
 * # Returns
 * - Number of characters actually written (excluding null terminator)
 *
 * # Safety
 * - `msg` must be a valid pointer to a buffer with at least `len` bytes
 * - The buffer must be large enough to hold the error message including null terminator
 * - If the message is longer than `len - 1`, it will be truncated
 */
int32_t linkrs_errmsg(char *msg, uintptr_t len);

/**
 * Retrieve the string description corresponding to the error code (similar to sqlite3_errstr in SQLite).
 *
 * # Parameter
 * - `code`: Error Code
 *
 * # Return
 * Error description string (static lifecycle; no need for release)
 */
const char *linkrs_errstr(int32_t code);

/**
 * Get the location of the SQL error (in terms of character offset).
 *
 * # Parameters
 * - `session`: session handle
 *
 * # Returns
 * - Character offset of the error location, if there is no error or invalid session return -1
 */
int linkrs_error_offset(struct linkrs_session_t *session);

/**
 * Get Extended Error Code
 *
 * # Parameters
 * - `session`: session handle
 *
 * # Returns
 * - Extended error code, returns 0 if no error or invalid session (LINKRS_EXTENDED_NONE)
 */
int linkrs_extended_errcode(struct linkrs_session_t *session);

/**
 * Create a custom scalar function
 *
 * # Arguments
 * - `session`: Session handle
 * - `name`: Function name
 * - `argc`: Number of arguments, -1 for variable arguments
 * - `user_data`: User data pointer
 * - `x_func`: Scalar function callback
 * - `x_destroy`: Destructor callback, can be NULL
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Example
 * ```c
 * extern void my_function(linkrs_context_t* ctx, int argc, linkrs_value_t* argv) {
 *     // Implement function logic
 * }
 *
 * linkrs_create_function(session, "my_func", 2, NULL, my_function, NULL);
 * ```
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `name` must be a valid pointer to a null-terminated UTF-8 string
 * - `x_func` must be a valid function pointer
 * - `user_data` is passed to the callback and must remain valid for the lifetime of the function
 */
int linkrs_create_function(struct linkrs_session_t *session,
                           const char *name,
                           int argc,
                           void *user_data,
                           linkrs_scalar_function_callback x_func,
                           linkrs_function_destroy_callback _x_destroy);

/**
 * Creating custom aggregate functions
 *
 * # Arguments
 * - `session`: Session handle
 * - `name`: Function name
 * - `argc`: Number of arguments, -1 for variable arguments
 * - `user_data`: User data pointer
 * - `x_step`: Aggregate step callback
 * - `x_final`: Aggregate final callback
 * - `x_destroy`: Destructor callback, can be NULL
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `name` must be a valid pointer to a null-terminated UTF-8 string
 * - `x_step` and `x_final` must be valid function pointers
 * - `user_data` is passed to the callbacks and must remain valid for the lifetime of the function
 */
int linkrs_create_aggregate(struct linkrs_session_t *session,
                            const char *name,
                            int argc,
                            void *user_data,
                            linkrs_aggregate_step_callback x_step,
                            linkrs_aggregate_final_callback x_final,
                            linkrs_function_destroy_callback _x_destroy);

/**
 * Delete the custom function.
 *
 * # Arguments
 * - `session`: Session handle
 * - `name`: Function name
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `name` must be a valid pointer to a null-terminated UTF-8 string
 */
int linkrs_delete_function(struct linkrs_session_t *session, const char *name);

/**
 * Setting the return value of a function
 *
 * # Arguments
 * - `context`: Function execution context
 * - `value`: Return value
 *
 * # Description
 * Call this function in the scalar function or aggregate function's xFinal callback to set the return value
 *
 * # Safety
 * - `context` must be a valid function context pointer passed to the callback
 * - `value` must be a valid pointer to a value structure, or NULL to set a null result
 * - This function should only be called from within a registered function callback
 */
int linkrs_context_set_result(struct linkrs_context_t *context,
                              const struct linkrs_value_t *value);

/**
 * Obtaining the type of the value returned by a function
 *
 * # Arguments
 * - `context`: Function execution context
 *
 * # Returns
 * - Value type
 *
 * # Safety
 * - `context` must be a valid function context pointer passed to the callback
 * - This function should only be called from within a registered function callback
 */
enum linkrs_value_type_t linkrs_context_result_type(struct linkrs_context_t *context);

/**
 * Setting error messages
 *
 * # Arguments
 * - `context`: Function execution context
 * - `error_msg`: Error message
 *
 * # Description
 * Call this function to set an error message when the function execution fails
 *
 * # Safety
 * - `context` must be a valid function context pointer passed to the callback
 * - `error_msg` must be a valid pointer to a null-terminated UTF-8 string
 * - This function should only be called from within a registered function callback
 */
int linkrs_context_set_error(struct linkrs_context_t *context, const char *error_msg);

/**
 * Obtain parameter values from the context (auxiliary function)
 *
 * # Arguments
 * - `context`: Function execution context
 * - `index`: Argument index
 *
 * # Returns
 * - Argument value pointer, returns NULL if index is out of bounds
 *
 * # Safety
 * - `context` must be a valid function context pointer passed to the callback
 * - `index` must be a valid argument index (0 <= index < argc)
 * - The returned pointer is only valid for the duration of the callback
 * - This function should only be called from within a registered function callback
 */
const struct linkrs_value_t *linkrs_context_get_arg(struct linkrs_context_t *context, int index);

/**
 * Get the number of parameters
 *
 * # Arguments
 * - `context`: Function execution context
 *
 * # Returns
 * - Number of arguments
 *
 * # Safety
 * - `context` must be a valid function context pointer passed to the callback
 * - This function should only be called from within a registered function callback
 */
int linkrs_context_arg_count(struct linkrs_context_t *context);

/**
 * Load a UDF dynamic library and register the exported function.
 *
 * # Arguments
 * - `session`: Session handle
 * - `path`: Null-terminated UTF-8 path to the `.so` / `.dylib` / `.dll` file
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `path` must be a valid pointer to a null-terminated UTF-8 string
 */
int linkrs_load_extension(struct linkrs_session_t *session, const char *path);

/**
 * Unload a previously loaded dynamic UDF by function name.
 *
 * # Arguments
 * - `session`: Session handle
 * - `name`: Null-terminated UTF-8 function name
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `name` must be a valid pointer to a null-terminated UTF-8 string
 */
int linkrs_unload_extension(struct linkrs_session_t *session, const char *name);

/**
 * Reload a dynamic UDF from its original library path.
 *
 * # Arguments
 * - `session`: Session handle
 * - `name`: Null-terminated UTF-8 function name
 * - `reloaded`: Out-parameter set to 1 when the library was reloaded,
 *   0 when the file is unchanged and reloading was skipped
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `name` must be a valid pointer to a null-terminated UTF-8 string
 * - `reloaded` must be a valid writable pointer (may be NULL to ignore)
 */
int linkrs_reload_extension(struct linkrs_session_t *session, const char *name, int *reloaded);

/**
 * Execute a migration plan given as JSON.
 *
 * Runs through the shared online orchestration: writes stall only across
 * schema-modifying steps while the data backfill stays online.
 *
 * # Arguments
 * - `db`: Database handle
 * - `plan_json`: Null-terminated JSON string of `MigrationPlan`
 *
 * # Returns
 * - On success: pointer to `linkrs_migration_report_t` (must be freed with `linkrs_migration_report_free`)
 * - On failure: null pointer (error details via `linkrs_errmsg`)
 *
 * # Safety
 * - `db` must be a valid handle from `linkrs_open`
 * - `plan_json` must be a valid null-terminated UTF-8 string
 * - Returned pointer must be freed by caller
 */
struct linkrs_migration_report_t *linkrs_migration_execute(struct linkrs_t *db,
                                                           const char *plan_json);

/**
 * Free a migration report returned by `linkrs_migration_execute`.
 *
 * # Safety
 * - `report` must be a valid pointer from `linkrs_migration_execute` or null
 */
void linkrs_migration_report_free(struct linkrs_migration_report_t *report);

/**
 * Generate a migration plan and return it as JSON string.
 *
 * Caller must free the returned string with `linkrs_free_string`.
 *
 * # Safety
 * - `db` must be valid
 * - `space`, `label` must be valid null-terminated strings
 */
char *linkrs_migration_plan_json(struct linkrs_t *db,
                                 const char *space,
                                 const char *label,
                                 int is_edge,
                                 uint64_t from_version,
                                 uint64_t to_version,
                                 int expand_contract);

/**
 * Roll back a migration plan given as JSON.
 *
 * Runs a generated rollback plan when one exists, otherwise restores from
 * the pre-migration backup when one was taken.
 *
 * # Arguments
 * - `db`: Database handle
 * - `plan_json`: Null-terminated JSON string of `MigrationPlan`
 *
 * # Returns
 * - On success: pointer to `linkrs_migration_report_t` (must be freed with `linkrs_migration_report_free`)
 * - On failure: null pointer (error details via `linkrs_errmsg`)
 *
 * # Safety
 * - `db` must be a valid handle from `linkrs_open`
 * - `plan_json` must be a valid null-terminated UTF-8 string
 * - Returned pointer must be freed by caller
 */
struct linkrs_migration_report_t *linkrs_migration_rollback(struct linkrs_t *db,
                                                            const char *plan_json);

/**
 * Perform a simple query
 *
 * # Arguments
 * - `session`: Session handle
 * - `query`: Query statement (UTF-8 encoded)
 * - `result`: Output parameter, result set handle
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `query` must be a valid pointer to a null-terminated UTF-8 string
 * - `result` must be a valid pointer to store the result handle
 * - The caller is responsible for freeing the result handle using `linkrs_result_free` when done
 */
int linkrs_execute(struct linkrs_session_t *session,
                   const char *query,
                   struct linkrs_result_t **result);

/**
 * Execute a parameterized query
 *
 * Positional binding: `params[i]` binds to the `@param_{i}` query
 * parameter (e.g. `params[0]` fills `@param_0`). This mirrors the Rust
 * `Session::execute_with_params` named-parameter map with synthesized
 * `param_{i}` keys.
 *
 * # Arguments
 * - `session`: Session handle
 * - `query`: Query statement (UTF-8 encoded)
 * - `params`: Parameter array
 * - `param_count`: Number of parameters
 * - `result`: Output parameter, result set handle
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `query` must be a valid pointer to a null-terminated UTF-8 string
 * - `result` must be a valid pointer to store the result handle
 * - If `params` is not NULL, it must point to at least `param_count` valid `linkrs_value_t` elements
 * - The caller is responsible for freeing the result handle using `linkrs_result_free` when done
 */
int linkrs_execute_params(struct linkrs_session_t *session,
                          const char *query,
                          const struct linkrs_value_t *params,
                          uintptr_t param_count,
                          struct linkrs_result_t **result);

/**
 * Releasing the result set
 *
 * # Arguments
 * - `result`: Result set handle
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `result` must be a valid result handle created by `linkrs_execute` or `linkrs_execute_params`
 * - After calling this function, the result handle becomes invalid and must not be used
 * - Any string pointers obtained from this result set become invalid after this call
 */
int linkrs_result_free(struct linkrs_result_t *result);

/**
 * Get the number of columns in the result set
 *
 * # Arguments
 * - `result`: Result set handle
 *
 * # Returns
 * - Number of columns, returns -1 on error
 *
 * # Safety
 * - `result` must be a valid result handle created by `linkrs_execute` or `linkrs_execute_params`
 */
int linkrs_column_count(struct linkrs_result_t *result);

/**
 * Get the number of rows in the result set
 *
 * # Arguments
 * - `result`: Result set handle
 *
 * # Returns
 * - Number of rows, returns -1 on error
 *
 * # Safety
 * - `result` must be a valid result handle created by `linkrs_execute` or `linkrs_execute_params`
 */
int linkrs_row_count(struct linkrs_result_t *result);

/**
 * Getting Column Names
 *
 * # Arguments
 * - `result`: Result set handle
 * - `index`: Column index (starting from 0)
 *
 * # Returns
 * - Column name (UTF-8 encoded), returns NULL on error
 *
 * # Memory Management
 * The returned string is dynamically allocated and must be freed by the caller using `linkrs_free_string`
 * to avoid memory leaks.
 *
 * # Safety
 * - `result` must be a valid result handle created by `linkrs_execute` or `linkrs_execute_params`
 * - `index` must be a valid column index (0 <= index < column count)
 * - The returned pointer must be freed by the caller to avoid memory leaks
 */
char *linkrs_column_name(struct linkrs_result_t *result,
                         int index);

/**
 * Get integer value
 *
 * # Arguments
 * - `result`: Result set handle
 * - `row`: Row index (starting from 0)
 * - `col`: Column name (UTF-8 encoded)
 * - `value`: Output parameter, integer value
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `result` must be a valid result handle created by `linkrs_execute` or `linkrs_execute_params`
 * - `col` must be a valid pointer to a null-terminated UTF-8 string
 * - `value` must be a valid pointer to store the result
 * - `row` must be a valid row index (0 <= row < row count)
 */
int linkrs_get_int(struct linkrs_result_t *result, int row, const char *col, int64_t *value);

/**
 * Getting String Values
 *
 * # Arguments
 * - `result`: Result set handle
 * - `row`: Row index (starting from 0)
 * - `col`: Column name (UTF-8 encoded)
 * - `len`: Output parameter, string length
 *
 * # Returns
 * - String value (UTF-8 encoded), returns NULL on error
 *
 * # Memory Management
 * The returned string is dynamically allocated and must be freed by the caller using `linkrs_free_string`
 * to avoid memory leaks.
 *
 * # Safety
 * - `result` must be a valid result handle created by `linkrs_execute` or `linkrs_execute_params`
 * - `col` must be a valid pointer to a null-terminated UTF-8 string
 * - `len` must be a valid pointer to store the string length, or NULL if not needed
 * - `row` must be a valid row index (0 <= row < row count)
 * - The returned pointer must be freed by the caller to avoid memory leaks
 */
char *linkrs_get_string(struct linkrs_result_t *result,
                        int row,
                        const char *col,
                        int *len);

/**
 * Get Binary Data
 *
 * # Arguments
 * - `result`: Result set handle
 * - `row`: Row index (starting from 0)
 * - `col`: Column name (UTF-8 encoded)
 * - `len`: Output parameter, data length (in bytes)
 *
 * # Returns
 * - Data pointer, returns NULL on error
 *
 * # Note
 * The returned pointer's lifetime is bound to the result set; the caller should not free it
 *
 * # Safety
 * - `result` must be a valid result handle created by `linkrs_execute` or `linkrs_execute_params`
 * - `col` must be a valid pointer to a null-terminated UTF-8 string
 * - `len` must be a valid pointer to store the data length, or NULL if not needed
 * - `row` must be a valid row index (0 <= row < row count)
 * - The returned pointer is only valid as long as the result set is not freed
 */
const uint8_t *linkrs_get_blob(struct linkrs_result_t *result, int row, const char *col, int *len);

/**
 * Get integer values (indexed by column)
 *
 * # Arguments
 * - `result`: Result set handle
 * - `row`: Row index (starting from 0)
 * - `col`: Column index (starting from 0)
 * - `value`: Output parameter, integer value
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `result` must be a valid result handle created by `linkrs_execute` or `linkrs_execute_params`
 * - `value` must be a valid pointer to store the result
 * - `row` must be a valid row index (0 <= row < row count)
 * - `col` must be a valid column index (0 <= col < column count)
 */
int linkrs_get_int_by_index(struct linkrs_result_t *result, int row, int col, int64_t *value);

/**
 * Get string value (indexed by column)
 *
 * # Arguments
 * - `result`: Result set handle
 * - `row`: Row index (starting from 0)
 * - `col`: Column index (starting from 0)
 * - `len`: Output parameter, string length
 *
 * # Returns
 * - String value (UTF-8 encoded), returns NULL on error
 *
 * # Memory Management
 * The returned string is dynamically allocated and must be freed by the caller using `linkrs_free_string`
 * to avoid memory leaks.
 *
 * # Safety
 * - `result` must be a valid result handle created by `linkrs_execute` or `linkrs_execute_params`
 * - `len` must be a valid pointer to store the string length, or NULL if not needed
 * - `row` must be a valid row index (0 <= row < row count)
 * - `col` must be a valid column index (0 <= col < column count)
 * - The returned pointer must be freed by the caller to avoid memory leaks
 */
char *linkrs_get_string_by_index(struct linkrs_result_t *result,
                                 int row,
                                 int col,
                                 int *len);

/**
 * Get Boolean value (indexed by column)
 *
 * # Arguments
 * - `result`: Result set handle
 * - `row`: Row index (starting from 0)
 * - `col`: Column index (starting from 0)
 * - `value`: Output parameter, boolean value
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `result` must be a valid result handle created by `linkrs_execute` or `linkrs_execute_params`
 * - `value` must be a valid pointer to store the result
 * - `row` must be a valid row index (0 <= row < row count)
 * - `col` must be a valid column index (0 <= col < column count)
 */
int linkrs_get_bool_by_index(struct linkrs_result_t *result, int row, int col, bool *value);

/**
 * Get floating point values (indexed by column)
 *
 * # Arguments
 * - `result`: Result set handle
 * - `row`: Row index (starting from 0)
 * - `col`: Column index (starting from 0)
 * - `value`: Output parameter, float value
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `result` must be a valid result handle created by `linkrs_execute` or `linkrs_execute_params`
 * - `value` must be a valid pointer to store the result
 * - `row` must be a valid row index (0 <= row < row count)
 * - `col` must be a valid column index (0 <= col < column count)
 */
int linkrs_get_float_by_index(struct linkrs_result_t *result, int row, int col, double *value);

/**
 * Get binary data (indexed by column)
 *
 * # Arguments
 * - `result`: Result set handle
 * - `row`: Row index (starting from 0)
 * - `col`: Column index (starting from 0)
 * - `len`: Output parameter, data length (in bytes)
 *
 * # Returns
 * - Data pointer, returns NULL on error
 *
 * # Note
 * The returned pointer's lifetime is bound to the result set; the caller should not free it
 *
 * # Safety
 * - `result` must be a valid result handle created by `linkrs_execute` or `linkrs_execute_params`
 * - `len` must be a valid pointer to store the data length, or NULL if not needed
 * - `row` must be a valid row index (0 <= row < row count)
 * - `col` must be a valid column index (0 <= col < column count)
 * - The returned pointer is only valid as long as the result set is not freed
 */
const uint8_t *linkrs_get_blob_by_index(struct linkrs_result_t *result, int row, int col, int *len);

/**
 * Get column type
 *
 * # Arguments
 * - `result`: Result set handle
 * - `col`: Column index (starting from 0)
 *
 * # Returns
 * - Column type, returns LINKRS_NULL on error
 *
 * # Safety
 * - `result` must be a valid result handle created by `linkrs_execute` or `linkrs_execute_params`
 * - `col` must be a valid column index (0 <= col < column count)
 */
enum linkrs_value_type_t linkrs_column_type(struct linkrs_result_t *result, int col);

/**
 * Get the query execution time in milliseconds.
 *
 * # Arguments
 * - `result`: Result set handle
 * - `out_ms`: Output parameter, execution time in milliseconds
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `result` must be a valid result handle created by `linkrs_execute` or `linkrs_execute_params`
 * - `out_ms` must be a valid pointer to store the result
 */
int linkrs_result_execution_time_ms(struct linkrs_result_t *result, uint64_t *out_ms);

/**
 * Get the number of rows scanned while producing the result set.
 *
 * # Arguments
 * - `result`: Result set handle
 * - `out_rows`: Output parameter, scanned row count
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `result` must be a valid result handle created by `linkrs_execute` or `linkrs_execute_params`
 * - `out_rows` must be a valid pointer to store the result
 */
int linkrs_result_rows_scanned(struct linkrs_result_t *result, uint64_t *out_rows);

/**
 * Create a session
 *
 * # Arguments
 * - `db`: Database handle
 * - `session`: Output parameter, session handle
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `db` must be a valid database handle created by `linkrs_open` or `linkrs_open_with_config`
 * - `session` must be a valid pointer to store the session handle
 * - The caller is responsible for closing the session using `linkrs_session_close` when done
 * - The session handle must not be used after closing
 */
int linkrs_session_create(struct linkrs_t *db, struct linkrs_session_t **session);

/**
 * Close the session.
 *
 * # Arguments
 * - `session`: Session handle
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - After calling this function, the session handle becomes invalid and must not be used
 * - All pending transactions will be rolled back
 */
int linkrs_session_close(struct linkrs_session_t *session);

/**
 * Switch to the image space
 *
 * # Arguments
 * - `session`: Session handle
 * - `space_name`: Graph space name (UTF-8 encoded)
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `space_name` must be a valid pointer to a null-terminated UTF-8 string
 */
int linkrs_session_use_space(struct linkrs_session_t *session, const char *space_name);

/**
 * Obtain the current image space
 *
 * # Arguments
 * - `session`: Session handle
 *
 * # Returns
 * - Current graph space name (UTF-8 encoded), returns NULL if none
 *
 * # Memory Management
 * The returned string is dynamically allocated and must be freed by the caller using `linkrs_free_string`
 * to avoid memory leaks.
 *
 * # Example
 * ```c
 * char* space = linkrs_session_current_space(session);
 * if (space) {
 *     printf("Current space: %s\n", space);
 *     linkrs_free_string(space);  // Must free
 * }
 * ```
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - The returned pointer must be freed by the caller to avoid memory leaks
 */
char *linkrs_session_current_space(struct linkrs_session_t *session);

/**
 * Enable the automatic submission mode.
 *
 * # Arguments
 * - `session`: Session handle
 * - `autocommit`: Whether to enable autocommit
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 */
int linkrs_session_set_autocommit(struct linkrs_session_t *session, bool autocommit);

/**
 * Enable the automatic submission mode.
 *
 * # Arguments
 * - `session`: Session handle
 *
 * # Returns
 * - Whether autocommit is enabled
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 */
bool linkrs_session_get_autocommit(struct linkrs_session_t *session);

/**
 * Setting the busy wait timeout
 *
 * # Arguments
 * - `session`: Session handle
 * - `timeout_ms`: Timeout in milliseconds
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 */
int linkrs_busy_timeout(struct linkrs_session_t *session, int timeout_ms);

/**
 * Busy wait timeout has occurred.
 *
 * # Arguments
 * - `session`: Session handle
 *
 * # Returns
 * - Timeout in milliseconds, returns -1 on error
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 */
int linkrs_busy_timeout_get(struct linkrs_session_t *session);

/**
 * Setting up an SQL tracing callback
 *
 * # Arguments
 * - `session`: Session handle
 * - `callback`: Trace callback function, NULL to disable tracing
 * - `user_data`: User data pointer, will be passed to the callback
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Example
 * ```c
 * extern void my_trace_callback(const char* sql, void* data) {
 *     printf("Executing: %s\n", sql);
 * }
 *
 * linkrs_trace(session, my_trace_callback, NULL);
 * ```
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `callback` must be a valid function pointer, or NULL to disable tracing
 * - `user_data` is passed to the callback and must remain valid for the lifetime of the callback
 */
int linkrs_trace(struct linkrs_session_t *session, linkrs_trace_callback callback, void *user_data);

/**
 * Setting up the commit hook
 *
 * # Arguments
 * - `session`: Session handle
 * - `callback`: Commit hook callback function, NULL to disable the hook
 * - `user_data`: User data pointer, will be passed to the callback
 *
 * # Returns
 * - Previous hook user data pointer (if any)
 *
 * # Description
 * The commit hook is called before a transaction is committed. If the callback returns a non-zero value,
 * the transaction will be rolled back.
 *
 * The C callback is bridged into the transaction manager's commit-veto
 * registry, so it shares one evaluation point with Rust
 * `register_commit_veto` hooks (first veto wins). A panicking callback is
 * isolated and treated as allow.
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `callback` must be a valid function pointer, or NULL to disable the hook
 * - `user_data` is passed to the callback and must remain valid for the lifetime of the callback
 */
void *linkrs_commit_hook(struct linkrs_session_t *session,
                         linkrs_commit_hook_callback callback,
                         void *user_data);

/**
 * Setting up a rollback hook
 *
 * # Arguments
 * - `session`: Session handle
 * - `callback`: Rollback hook callback function, NULL to disable the hook
 * - `user_data`: User data pointer, will be passed to the callback
 *
 * # Returns
 * - Previous hook user data pointer (if any)
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `callback` must be a valid function pointer, or NULL to disable the hook
 * - `user_data` is passed to the callback and must remain valid for the lifetime of the callback
 */
void *linkrs_rollback_hook(struct linkrs_session_t *session,
                           linkrs_rollback_hook_callback callback,
                           void *user_data);

/**
 * Set up the update hook
 *
 * When data in the database changes, the callback function is called
 *
 * # Arguments
 * - `session`: Session handle
 * - `callback`: Update hook callback function, NULL to disable the hook
 * - `user_data`: User data pointer, will be passed to the callback
 *
 * # Returns
 * - Previous hook user data pointer (if any)
 *
 * # Callback Parameters
 * - `operation`: Operation type (1=INSERT, 2=UPDATE, 3=DELETE)
 * - `database`: Database/space name
 * - `table`: Table name (empty string for graph database)
 * - `rowid`: Affected row ID
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `callback` must be a valid function pointer, or NULL to disable the hook
 * - `user_data` is passed to the callback and must remain valid for the lifetime of the callback
 */
void *linkrs_update_hook(struct linkrs_session_t *session,
                         linkrs_update_hook_callback callback,
                         void *user_data);

/**
 * Interrupt a session's next query.
 *
 * Cooperative cancellation at the entry gate: sets the session interrupt
 * flag so the next `execute` entry point fails fast with an interrupted
 * error. A query already running is not touched; stop those through the
 * executor kill path. Use `linkrs_connection_clear_interrupt` to resume
 * normal execution.
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 */
int linkrs_connection_interrupt(struct linkrs_session_t *session);

/**
 * Clear a previously requested session interrupt.
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 */
int linkrs_connection_clear_interrupt(struct linkrs_session_t *session);

/**
 * Get the number of rows affected by the last operation
 *
 * # Arguments
 * - `session`: Session handle
 *
 * # Returns
 * - Number of rows affected, returns 0 on error
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 */
uint64_t linkrs_session_changes(struct linkrs_session_t *session);

/**
 * Get the total number of rows affected
 *
 * # Arguments
 * - `session`: Session handle
 *
 * # Returns
 * - Total number of rows affected, returns 0 on error
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 */
uint64_t linkrs_session_total_changes(struct linkrs_session_t *session);

/**
 * Get the ID of the last inserted vertex
 *
 * # Arguments
 * - `session`: Session handle
 * - `vertex_id`: Output parameter, vertex ID
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code (LINKRS_NOTFOUND if no vertex was inserted)
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `vertex_id` must be a valid pointer to store the result
 */
int linkrs_session_last_insert_vertex_id(struct linkrs_session_t *session, uint64_t *vertex_id);

/**
 * Get the ID of the last inserted edge
 *
 * # Arguments
 * - `session`: Session handle
 * - `edge_id`: Output parameter, edge ID
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code (LINKRS_NOTFOUND if no edge was inserted)
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `edge_id` must be a valid pointer to store the result
 */
int linkrs_session_last_insert_edge_id(struct linkrs_session_t *session, uint64_t *edge_id);

/**
 * Get session statistics (total changes)
 *
 * # Arguments
 * - `session`: Session handle
 * - `stats`: Output parameter, statistics structure
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 */
int linkrs_session_get_statistics(struct linkrs_session_t *session,
                                  struct linkrs_session_statistics_t *stats);

/**
 * Begin a transaction
 *
 * # Parameters
 * - `session`: session handle
 * - `txn`: output parameter, transaction handle
 *
 * # Return
 * Success: LINKRS_OK
 * Failure: Error code
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `txn` must be a valid pointer to store the transaction handle
 * - The session must not have been closed
 * - The caller is responsible for freeing the transaction using `linkrs_txn_free` when done
 */
int linkrs_txn_begin(struct linkrs_session_t *session, struct linkrs_txn_t **txn);

/**
 * Starting a read-only transaction
 *
 * # Parameters
 * - `session`: Session handle
 * - `txn`: Output parameter, transaction handle
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `session` must be a valid session handle created by `linkrs_session_create`
 * - `txn` must be a valid pointer to store the transaction handle
 * - The session must not have been closed
 * - The caller is responsible for freeing the transaction using `linkrs_txn_free` when done
 */
int linkrs_txn_begin_readonly(struct linkrs_session_t *session, struct linkrs_txn_t **txn);

/**
 * Executing queries in a transaction
 *
 * # Parameters
 * - `txn`: Transaction handle
 * - `query`: Query statement (UTF-8 encoding)
 * - `result`: Output parameter, result set handle
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `txn` must be a valid transaction handle created by `linkrs_txn_begin` or `linkrs_txn_begin_readonly`
 * - `query` must be a valid pointer to a null-terminated UTF-8 string
 * - `result` must be a valid pointer to store the result handle
 * - The transaction must not have been committed or rolled back
 * - The caller is responsible for freeing the result using `linkrs_result_free` when done
 */
int linkrs_txn_execute(struct linkrs_txn_t *txn,
                       const char *query,
                       struct linkrs_result_t **result);

/**
 * Commit transactions
 *
 * # Parameters
 * - `txn`: Transaction handle
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `txn` must be a valid transaction handle created by `linkrs_txn_begin` or `linkrs_txn_begin_readonly`
 * - The transaction must not have been committed or rolled back already
 * - The associated session must still be valid
 * - After calling this function, the transaction handle should be freed using `linkrs_txn_free`
 */
int linkrs_txn_commit(struct linkrs_txn_t *txn);

/**
 * Rolling back transactions
 *
 * # Parameters
 * - `txn`: Transaction handle
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `txn` must be a valid transaction handle created by `linkrs_txn_begin` or `linkrs_txn_begin_readonly`
 * - The transaction must not have been committed or rolled back already
 * - The associated session must still be valid
 * - After calling this function, the transaction handle should be freed using `linkrs_txn_free`
 */
int linkrs_txn_rollback(struct linkrs_txn_t *txn);

/**
 * Creating a savepoint
 *
 * # Parameters
 * - `txn`: Transaction handle
 * - `name`: Name of the savepoint (UTF-8 encoding)
 *
 * # Returns
 * - Success: Savepoint ID
 * - Failure: -1
 *
 * # Safety
 * - `txn` must be a valid transaction handle created by `linkrs_txn_begin` or `linkrs_txn_begin_readonly`
 * - `name` must be a valid pointer to a null-terminated UTF-8 string
 * - The transaction must not have been committed or rolled back
 */
int64_t linkrs_txn_savepoint(struct linkrs_txn_t *txn,
                             const char *name);

/**
 * Release the savepoint.
 *
 * # Parameters
 * - `txn`: Transaction handle
 * - `savepoint_id`: ID of the savepoint
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `txn` must be a valid transaction handle created by `linkrs_txn_begin` or `linkrs_txn_begin_readonly`
 * - `savepoint_id` must be a valid savepoint ID returned by `linkrs_txn_savepoint`
 * - The transaction must not have been committed or rolled back
 */
int linkrs_txn_release_savepoint(struct linkrs_txn_t *txn,
                                 int64_t savepoint_id);

/**
 * Roll back to the savepoint.
 *
 * # Parameters
 * - `txn`: Transaction handle
 * - `savepoint_id`: Savepoint ID
 *
 * # Returns
 * - Success: LINKRS_OK
 * - Failure: Error code
 *
 * # Safety
 * - `txn` must be a valid transaction handle created by `linkrs_txn_begin` or `linkrs_txn_begin_readonly`
 * - `savepoint_id` must be a valid savepoint ID returned by `linkrs_txn_savepoint`
 * - The transaction must not have been committed or rolled back
 */
int linkrs_txn_rollback_to_savepoint(struct linkrs_txn_t *txn,
                                     int64_t savepoint_id);

/**
 * Free the transaction handle
 *
 * # Parameters
 * - `txn`: Transaction handle
 *
 * # Safety
 * - `txn` must be a valid transaction handle created by `linkrs_txn_begin` or `linkrs_txn_begin_readonly`
 * - `txn` can be null (in which case this function does nothing)
 * - After calling this function, the handle is invalid and must not be used again
 */
void linkrs_txn_free(struct linkrs_txn_t *txn);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LINKRS_H */
